-- =====================================================================================
-- Srichand AI Beauty Advisor — prototype database
-- PostgreSQL flavour. `scripts/make_postgres_schema.py`
-- converts it to db/schema.postgres.sql (BIGINT identity keys, TIMESTAMPTZ, JSONB).
--
-- Conventions
--   * BOOLEAN columns hold 0/1 in SQLite.  * TIMESTAMPTZ columns hold ISO-8601 UTC strings.
--   * JSON columns hold JSON text.         * Money is NUMERIC(10,2) in THB unless stated.
--   * Every table is registered in `data_provenance` as real_sourced / derived /
--     curated_knowledge / mock, so nobody mistakes simulated operations for client data.
-- Sections: 0 Meta · 1 Catalogue · 2 Ingredients · 3 Advisor knowledge · 4 Commerce
--           5 Loyalty · 6 Advisor sessions (PDPA) · 7 Views
-- =====================================================================================
-- PostgreSQL 14+ flavour, generated by scripts/05_meta.py from db/schema.sql — do not edit by hand.

-- ───────────────────────────── 0. META ─────────────────────────────
CREATE TABLE data_sources (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code          TEXT NOT NULL UNIQUE,            -- e.g. 'srichand_store_api'
  name          TEXT NOT NULL,
  url           TEXT,
  source_type   TEXT NOT NULL CHECK (source_type IN ('official','retailer','third_party_db','regulator','news','curated','internal_mock')),
  accessed_at   TIMESTAMPTZ,
  notes         TEXT
);

CREATE TABLE data_provenance (
  table_name         TEXT PRIMARY KEY,
  origin             TEXT NOT NULL CHECK (origin IN ('real_sourced','derived','curated_knowledge','mock')),
  description        TEXT NOT NULL,
  production_source  TEXT                         -- what system replaces this table in production (ERP, OMS, CRM…)
);

-- ───────────────────────────── 1. CATALOGUE (real, sourced) ─────────────────────────────
CREATE TABLE brands (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug             TEXT NOT NULL UNIQUE,
  name_en          TEXT NOT NULL,
  name_th          TEXT NOT NULL,
  positioning      TEXT,
  target_audience  TEXT,
  price_tier       TEXT CHECK (price_tier IN ('value','mass','masstige')),
  site_url         TEXT,
  source_id        BIGINT REFERENCES data_sources(id)
);

CREATE TABLE product_lines (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  brand_id         BIGINT NOT NULL REFERENCES brands(id),
  slug             TEXT NOT NULL UNIQUE,
  name_en          TEXT NOT NULL,
  name_th          TEXT,
  domain           TEXT NOT NULL CHECK (domain IN ('skincare','sunscreen','powder','base_makeup','colour_makeup','lip','baby','hair','tools','mixed')),
  positioning_en   TEXT,                          -- one-line purpose of the line
  hero_ingredients JSONB,                          -- as named in official copy
  source_id        BIGINT REFERENCES data_sources(id)
);

CREATE TABLE categories (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parent_id   BIGINT REFERENCES categories(id),
  slug        TEXT NOT NULL UNIQUE,
  name_en     TEXT NOT NULL,
  name_th     TEXT,
  sort_order  INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE products (
  id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  brand_id              BIGINT NOT NULL REFERENCES brands(id),
  line_id               BIGINT REFERENCES product_lines(id),
  category_id           BIGINT REFERENCES categories(id),
  slug                  TEXT NOT NULL UNIQUE,
  name_en               TEXT NOT NULL,
  name_th               TEXT NOT NULL,
  product_type          TEXT NOT NULL CHECK (product_type IN ('single','set','gift_with_purchase','accessory','gift_card')),
  lifecycle_status      TEXT NOT NULL CHECK (lifecycle_status IN ('active','legacy','clearance_only')),
  tagline_th            TEXT,                     -- official short description
  description_th        TEXT,                     -- official long description (verbatim, HTML stripped)
  how_to_use            TEXT,                     -- official directions from the product page's how-to-use tab (verbatim)
  summary_en            TEXT,                     -- DERIVED: English summary of the official Thai copy
  texture               TEXT,
  finish                TEXT CHECK (finish IN ('matte','semi_matte','natural','satin','glowy','sheer','tone_up') OR finish IS NULL),
  coverage              TEXT CHECK (coverage IN ('none','sheer','light','medium','medium_to_full','full') OR coverage IS NULL),
  spf_value             TEXT,                     -- '50+', '35' … as printed
  pa_rating             TEXT,                     -- 'PA++++'
  oil_control_hours_claimed INTEGER,              -- official claim, e.g. 'คุมมัน 14 ชั่วโมง' -> 14
  is_water_resistant_claimed BOOLEAN,             -- official copy says กันน้ำ / waterproof
  free_from             JSONB,                     -- official "free from" claims e.g. ["paraben","fragrance"]
  is_fragrance_free     BOOLEAN,                  -- NULL = not stated
  is_alcohol_free       BOOLEAN,
  tested_claims_th      TEXT,                     -- official test footnotes (e.g. irritation test n=32, Dermaproof Asia)
  official_url          TEXT,
  image_url             TEXT,
  review_count_site     INTEGER,
  average_rating_site   NUMERIC(3,2),
  source_id             BIGINT NOT NULL REFERENCES data_sources(id),
  confidence            TEXT NOT NULL CHECK (confidence IN ('official','retailer','third_party','unverified')),
  verified_at           TIMESTAMPTZ NOT NULL,
  curation_notes        TEXT
);
CREATE INDEX idx_products_brand ON products(brand_id);
CREATE INDEX idx_products_line ON products(line_id);
CREATE INDEX idx_products_category ON products(category_id);

-- Every purchasable SKU (a size × shade, a sachet box, a multipack, a set) is one variant row.
CREATE TABLE product_variants (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id          BIGINT NOT NULL REFERENCES products(id),
  sku                 TEXT NOT NULL UNIQUE,       -- official SKU from the site
  variant_label       TEXT NOT NULL,              -- '30 ml', '9 g · 120 Beige', 'Box of 6 × 10 ml sachets'
  pack_format         TEXT NOT NULL CHECK (pack_format IN ('full_size','mini','sachet','sachet_box','multipack','set','gift','other')),
  units_per_pack      INTEGER NOT NULL DEFAULT 1,
  size_value          NUMERIC(8,2),
  size_unit           TEXT CHECK (size_unit IN ('ml','g') OR size_unit IS NULL),
  shade_code          TEXT,
  shade_name          TEXT,
  shade_undertone     TEXT CHECK (shade_undertone IN ('cool_pink','neutral','warm_yellow','warm_golden','peach','corrector') OR shade_undertone IS NULL),  -- DERIVED from official shade name
  shade_depth_rank    INTEGER,                    -- DERIVED: 1 = lightest within the product (from official shade numbering)
  shade_guidance_th   TEXT,                       -- official 'suits which skin tone' line, verbatim, where published
  list_price          NUMERIC(10,2) NOT NULL,     -- official regular price (THB)
  sale_price          NUMERIC(10,2),              -- official current price if discounted, else NULL
  currency            TEXT NOT NULL DEFAULT 'THB',
  web_in_stock        BOOLEAN NOT NULL,           -- srichand.com availability flag at snapshot time (real)
  is_listed_on_site   BOOLEAN NOT NULL DEFAULT TRUE,
  site_listing_id     BIGINT,
  site_variation_id   BIGINT,
  barcode             TEXT,                       -- not published; NULL until client master data is loaded
  price_checked_at    TIMESTAMPTZ NOT NULL
);
CREATE INDEX idx_variants_product ON product_variants(product_id);

CREATE TABLE bundle_components (
  bundle_variant_id     BIGINT NOT NULL REFERENCES product_variants(id),
  component_variant_id  BIGINT REFERENCES product_variants(id),   -- NULL when the component is not sold separately
  component_product_id  BIGINT REFERENCES products(id),
  component_label       TEXT NOT NULL,
  quantity              INTEGER NOT NULL DEFAULT 1,
  is_free_gift          BOOLEAN NOT NULL DEFAULT FALSE,
  PRIMARY KEY (bundle_variant_id, component_label)
);

-- Raw snapshot of all 345 public listings on srichand.com, mapped to the canonical product.
CREATE TABLE site_listings (
  site_listing_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id        BIGINT REFERENCES products(id),
  listing_name      TEXT NOT NULL,
  listing_type      TEXT NOT NULL CHECK (listing_type IN ('regular','sachet_box','multipack','set','gift','clearance','duplicate')),
  permalink         TEXT NOT NULL,
  regular_price     NUMERIC(10,2),
  current_price     NUMERIC(10,2),
  on_sale           BOOLEAN NOT NULL,
  in_stock          BOOLEAN NOT NULL,
  variation_count   INTEGER NOT NULL,
  image_url         TEXT,                         -- this listing's own shop photo (a 6-pack box shows its box, not the parent product shot)
  site_categories   JSONB,
  snapshot_at       TIMESTAMPTZ NOT NULL
);

CREATE TABLE product_images (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id  BIGINT NOT NULL REFERENCES products(id),
  url         TEXT NOT NULL,
  alt_text    TEXT,
  sort_order  INTEGER NOT NULL DEFAULT 0
);

-- Official claim sentences, kept verbatim so the agent quotes approved copy instead of inventing claims.
CREATE TABLE product_claims (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id     BIGINT NOT NULL REFERENCES products(id),
  claim_th       TEXT NOT NULL,
  claim_en       TEXT,                            -- DERIVED translation
  claim_type     TEXT NOT NULL CHECK (claim_type IN ('benefit','technology','ingredient_story','test_result','free_from','usage')),
  source_id      BIGINT NOT NULL REFERENCES data_sources(id)
);
CREATE INDEX idx_claims_product ON product_claims(product_id);

-- ───────────────────────────── 2. INGREDIENTS ─────────────────────────────
CREATE TABLE ingredients (                        -- curated cosmetic-science dictionary
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  inci_name          TEXT NOT NULL UNIQUE,
  common_name        TEXT,
  name_th            TEXT,
  ingredient_class   TEXT NOT NULL,               -- humectant, retinoid, uv_filter, vitamin_c, aha, bha, peptide, ceramide, emollient, soothing, brightener, absorbent, fragrance, preservative, solvent, other
  what_it_does_en    TEXT,
  what_it_does_th    TEXT,
  evidence_level     TEXT CHECK (evidence_level IN ('strong','moderate','emerging','cosmetic_only') OR evidence_level IS NULL),
  caution_en         TEXT,
  is_uv_filter       BOOLEAN NOT NULL DEFAULT FALSE,
  uv_coverage        TEXT,                        -- 'UVB', 'UVA1', 'UVA+UVB' …
  is_potential_irritant BOOLEAN NOT NULL DEFAULT FALSE,
  is_fragrance       BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE product_ingredients (
  product_id      BIGINT NOT NULL REFERENCES products(id),
  position        INTEGER NOT NULL,               -- order on the INCI list; 1 = highest concentration
  ingredient_id   BIGINT REFERENCES ingredients(id),   -- NULL if not yet in the dictionary
  inci_as_listed  TEXT NOT NULL,                  -- verbatim from the source
  is_key_active   BOOLEAN NOT NULL DEFAULT FALSE,
  source_id       BIGINT NOT NULL REFERENCES data_sources(id),
  source_url      TEXT,
  shade_scope     TEXT,                           -- for colour products the brand lists INCI per shade group; this is the group shown
  PRIMARY KEY (product_id, position)
);

-- Hero ingredients as named by the brand itself (available for every product, unlike full INCI).
CREATE TABLE product_hero_ingredients (
  product_id     BIGINT NOT NULL REFERENCES products(id),
  hero_name      TEXT NOT NULL,                   -- as written in official copy, e.g. 'Salicylic Acid Sphere'
  ingredient_id  BIGINT REFERENCES ingredients(id),
  official_benefit_th TEXT,
  PRIMARY KEY (product_id, hero_name)
);

CREATE TABLE ingredient_interactions (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  class_a          TEXT NOT NULL,                 -- ingredient_class or INCI name
  class_b          TEXT NOT NULL,
  interaction      TEXT NOT NULL CHECK (interaction IN ('avoid_same_session','introduce_gradually','pairs_well','requires_sunscreen')),
  advice_en        TEXT NOT NULL,
  advice_th        TEXT
);

-- ───────────────────────────── 3. ADVISOR KNOWLEDGE (curated) ─────────────────────────────
CREATE TABLE skin_types (
  id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug     TEXT NOT NULL UNIQUE,
  name_en  TEXT NOT NULL,
  name_th  TEXT NOT NULL,
  description_en TEXT
);

CREATE TABLE skin_concerns (
  id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug                  TEXT NOT NULL UNIQUE,
  name_en               TEXT NOT NULL,
  name_th               TEXT NOT NULL,
  concern_group         TEXT NOT NULL CHECK (concern_group IN ('oil_pores','acne','pigment','ageing','hydration_barrier','sensitivity','sun','makeup_goal')),
  photo_detectable      TEXT NOT NULL CHECK (photo_detectable IN ('yes','partly','no')),
  photo_cues_en         TEXT,                     -- what the vision model should look for
  cosmetic_wording_th   TEXT,                     -- Thai-FDA-safe way to talk about it
  refer_out_when_en     TEXT                      -- when to suggest seeing a dermatologist instead
);

CREATE TABLE product_concerns (
  product_id    BIGINT NOT NULL REFERENCES products(id),
  concern_id    BIGINT NOT NULL REFERENCES skin_concerns(id),
  relevance     INTEGER NOT NULL CHECK (relevance BETWEEN 1 AND 3),   -- 3 = primary purpose
  basis         TEXT NOT NULL CHECK (basis IN ('official_positioning','site_category','ingredient_inference')),
  rationale_en  TEXT,
  PRIMARY KEY (product_id, concern_id)
);

CREATE TABLE product_skin_types (
  product_id    BIGINT NOT NULL REFERENCES products(id),
  skin_type_id  BIGINT NOT NULL REFERENCES skin_types(id),
  suitability   TEXT NOT NULL CHECK (suitability IN ('ideal','good','caution')),
  basis         TEXT NOT NULL CHECK (basis IN ('official_positioning','ingredient_inference')),
  PRIMARY KEY (product_id, skin_type_id)
);

CREATE TABLE routine_steps (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug        TEXT NOT NULL UNIQUE,
  name_en     TEXT NOT NULL,
  name_th     TEXT NOT NULL,
  step_order  INTEGER NOT NULL,
  applies_am  BOOLEAN NOT NULL,
  applies_pm  BOOLEAN NOT NULL,
  is_makeup   BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE product_routine_steps (
  product_id     BIGINT NOT NULL REFERENCES products(id),
  step_id        BIGINT NOT NULL REFERENCES routine_steps(id),
  use_am         BOOLEAN NOT NULL,
  use_pm         BOOLEAN NOT NULL,
  frequency_en   TEXT,                            -- 'daily', '2–3 nights/week building up'
  usage_note_en  TEXT,
  PRIMARY KEY (product_id, step_id)
);

-- Needs the range cannot meet. The advisor is honest about these and may name a GENERIC
-- external option (never a competitor brand).
CREATE TABLE range_gaps (
  id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug                        TEXT NOT NULL UNIQUE,
  title_en                    TEXT NOT NULL,
  missing_category            TEXT NOT NULL,
  severity                    TEXT NOT NULL CHECK (severity IN ('high','medium','low')),
  why_it_matters_en           TEXT NOT NULL,
  closest_in_range_product_id BIGINT REFERENCES products(id),
  closest_in_range_limits_en  TEXT,
  generic_external_option_en  TEXT NOT NULL,
  generic_external_option_th  TEXT,
  commercial_read_en          TEXT
);

CREATE TABLE range_gap_concerns (
  gap_id      BIGINT NOT NULL REFERENCES range_gaps(id),
  concern_id  BIGINT NOT NULL REFERENCES skin_concerns(id),
  PRIMARY KEY (gap_id, concern_id)
);

-- ───────────────────────────── 4. COMMERCE (mock) ─────────────────────────────
CREATE TABLE warehouses (
  id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code      TEXT NOT NULL UNIQUE,
  name      TEXT NOT NULL,
  province  TEXT NOT NULL,
  serves    TEXT NOT NULL                          -- 'online_orders', 'retail_replenishment'
);

CREATE TABLE inventory (
  variant_id       BIGINT NOT NULL REFERENCES product_variants(id),
  warehouse_id     BIGINT NOT NULL REFERENCES warehouses(id),
  qty_on_hand      INTEGER NOT NULL CHECK (qty_on_hand >= 0),
  qty_reserved     INTEGER NOT NULL DEFAULT 0 CHECK (qty_reserved >= 0),
  reorder_point    INTEGER NOT NULL DEFAULT 0,
  next_restock_date TEXT,
  updated_at       TIMESTAMPTZ NOT NULL,
  PRIMARY KEY (variant_id, warehouse_id)
);

CREATE TABLE inventory_movements (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  variant_id     BIGINT NOT NULL REFERENCES product_variants(id),
  warehouse_id   BIGINT NOT NULL REFERENCES warehouses(id),
  movement_type  TEXT NOT NULL CHECK (movement_type IN ('receipt','sale','return','adjustment','reservation','release')),
  quantity       INTEGER NOT NULL,
  reference      TEXT,
  created_at     TIMESTAMPTZ NOT NULL
);

CREATE TABLE customers (
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  line_user_id       TEXT UNIQUE,                  -- LINE Messaging API userId (U + 32 hex). NULL for members who registered through the advisor: the hub owns the LINE ↔ member pairing
  line_display_name  TEXT,
  first_name         TEXT,
  last_name          TEXT,
  phone              TEXT,
  email              TEXT,
  birth_date         TEXT,
  gender             TEXT CHECK (gender IN ('female','male','non_binary','undisclosed') OR gender IS NULL),
  preferred_language TEXT NOT NULL DEFAULT 'th' CHECK (preferred_language IN ('th','en')),
  marketing_opt_in   BOOLEAN NOT NULL DEFAULT FALSE,
  phone_verified     BOOLEAN NOT NULL DEFAULT FALSE, -- TRUE once the mobile number has passed SMS OTP (the real Srichand Rewards sign-up does this)
  registration_channel TEXT NOT NULL DEFAULT 'line_rewards_form' CHECK (registration_channel IN ('line_rewards_form','line_oa_agent','website')),
  is_demo_persona    BOOLEAN NOT NULL DEFAULT FALSE,
  persona_brief      TEXT,                         -- demo script notes for the persona
  created_at         TIMESTAMPTZ NOT NULL
);

CREATE UNIQUE INDEX idx_customers_phone ON customers(phone);   -- one Rewards account per mobile number

CREATE TABLE customer_addresses (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id   BIGINT NOT NULL REFERENCES customers(id),
  label         TEXT NOT NULL,
  recipient     TEXT NOT NULL,
  phone         TEXT NOT NULL,
  address_line  TEXT NOT NULL,
  subdistrict   TEXT,
  district      TEXT,
  province      TEXT NOT NULL,
  postal_code   TEXT NOT NULL,
  is_default    BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE promotions (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code            TEXT NOT NULL UNIQUE,
  name_th         TEXT NOT NULL,
  name_en         TEXT,
  promo_type      TEXT NOT NULL CHECK (promo_type IN ('sale_price','bogo','gift_with_purchase','coupon','free_shipping','bundle_price','member_exclusive')),
  mechanics_en    TEXT NOT NULL,
  min_spend       NUMERIC(10,2),
  discount_type   TEXT CHECK (discount_type IN ('percent','amount','gift','shipping') OR discount_type IS NULL),
  discount_value  NUMERIC(10,2),
  gift_variant_id BIGINT REFERENCES product_variants(id),
  starts_at       TIMESTAMPTZ,
  ends_at         TIMESTAMPTZ,
  is_active       BOOLEAN NOT NULL DEFAULT TRUE,
  origin          TEXT NOT NULL CHECK (origin IN ('observed_on_site','mock'))
);

CREATE TABLE promotion_variants (
  promotion_id  BIGINT NOT NULL REFERENCES promotions(id),
  variant_id    BIGINT NOT NULL REFERENCES product_variants(id),
  PRIMARY KEY (promotion_id, variant_id)
);

CREATE TABLE coupons (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  promotion_id   BIGINT NOT NULL REFERENCES promotions(id),
  code           TEXT NOT NULL UNIQUE,
  customer_id    BIGINT REFERENCES customers(id), -- NULL = public code
  max_uses       INTEGER NOT NULL DEFAULT 1,
  used_count     INTEGER NOT NULL DEFAULT 0,
  expires_at     TIMESTAMPTZ
);

CREATE TABLE carts (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id  BIGINT NOT NULL REFERENCES customers(id),
  status       TEXT NOT NULL CHECK (status IN ('open','converted','abandoned')),
  created_at   TIMESTAMPTZ NOT NULL,
  updated_at   TIMESTAMPTZ NOT NULL
);

CREATE TABLE cart_items (
  cart_id      BIGINT NOT NULL REFERENCES carts(id),
  variant_id   BIGINT NOT NULL REFERENCES product_variants(id),
  quantity     INTEGER NOT NULL CHECK (quantity > 0),
  added_from   TEXT CHECK (added_from IN ('advisor_recommendation','search','reorder','promotion') OR added_from IS NULL),
  PRIMARY KEY (cart_id, variant_id)
);

CREATE TABLE orders (
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_number       TEXT NOT NULL UNIQUE,         -- 'SC-260918-0042'
  customer_id        BIGINT NOT NULL REFERENCES customers(id),
  channel            TEXT NOT NULL CHECK (channel IN ('line_oa_agent','website','line_shopping')),
  status             TEXT NOT NULL CHECK (status IN ('pending_payment','paid','packing','shipped','delivered','cancelled','refunded')),
  shipping_address_id BIGINT REFERENCES customer_addresses(id),
  subtotal           NUMERIC(10,2) NOT NULL,
  discount_total     NUMERIC(10,2) NOT NULL DEFAULT 0,
  shipping_fee       NUMERIC(10,2) NOT NULL DEFAULT 0,
  points_redeemed    INTEGER NOT NULL DEFAULT 0,
  points_discount    NUMERIC(10,2) NOT NULL DEFAULT 0,
  grand_total        NUMERIC(10,2) NOT NULL,
  coupon_id          BIGINT REFERENCES coupons(id),
  points_earned      INTEGER NOT NULL DEFAULT 0,
  source_session_id  BIGINT,                      -- advisor session that led to the order (attribution)
  placed_at          TIMESTAMPTZ NOT NULL,
  updated_at         TIMESTAMPTZ NOT NULL
);
CREATE INDEX idx_orders_customer ON orders(customer_id);

CREATE TABLE order_items (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id      BIGINT NOT NULL REFERENCES orders(id),
  variant_id    BIGINT NOT NULL REFERENCES product_variants(id),
  quantity      INTEGER NOT NULL CHECK (quantity > 0),
  unit_price    NUMERIC(10,2) NOT NULL,
  line_total    NUMERIC(10,2) NOT NULL,
  is_gift       BOOLEAN NOT NULL DEFAULT FALSE
);
CREATE INDEX idx_order_items_order ON order_items(order_id);

CREATE TABLE payments (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id        BIGINT NOT NULL REFERENCES orders(id),
  method          TEXT NOT NULL CHECK (method IN ('promptpay_qr','credit_card','mobile_banking','cod','truemoney','rabbit_line_pay')),
  status          TEXT NOT NULL CHECK (status IN ('pending','succeeded','failed','expired','refunded')),
  amount          NUMERIC(10,2) NOT NULL,
  gateway_ref     TEXT,
  qr_payload_ref  TEXT,                            -- mock reference to a PromptPay QR
  expires_at      TIMESTAMPTZ,
  paid_at         TIMESTAMPTZ,
  created_at      TIMESTAMPTZ NOT NULL
);

CREATE TABLE shipments (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id         BIGINT NOT NULL REFERENCES orders(id),
  warehouse_id     BIGINT NOT NULL REFERENCES warehouses(id),
  carrier          TEXT NOT NULL,
  tracking_number  TEXT NOT NULL UNIQUE,
  status           TEXT NOT NULL CHECK (status IN ('label_created','picked_up','in_transit','out_for_delivery','delivered','failed_attempt','returned')),
  shipped_at       TIMESTAMPTZ,
  estimated_delivery TEXT,
  delivered_at     TIMESTAMPTZ
);

CREATE TABLE shipment_events (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shipment_id   BIGINT NOT NULL REFERENCES shipments(id),
  status        TEXT NOT NULL,
  location      TEXT,
  description_th TEXT NOT NULL,
  occurred_at   TIMESTAMPTZ NOT NULL
);

-- ───────────────────────────── 5. LOYALTY (programme rules sourced where public; balances mock) ─────────────────────────────
CREATE TABLE loyalty_tiers (
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code               TEXT NOT NULL UNIQUE,
  name               TEXT NOT NULL,
  min_annual_spend   NUMERIC(10,2) NOT NULL,
  earn_rate_baht_per_point NUMERIC(10,2),
  benefits_en        TEXT,
  benefits_th        TEXT,
  origin             TEXT NOT NULL CHECK (origin IN ('official','assumed_for_demo'))
);

CREATE TABLE loyalty_accounts (
  customer_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY REFERENCES customers(id),
  member_number    TEXT NOT NULL UNIQUE,
  tier_id          BIGINT NOT NULL REFERENCES loyalty_tiers(id),
  points_balance   INTEGER NOT NULL DEFAULT 0,
  lifetime_points  INTEGER NOT NULL DEFAULT 0,
  spend_this_period NUMERIC(10,2) NOT NULL DEFAULT 0,
  tier_expires_on  TEXT,
  joined_at        TIMESTAMPTZ NOT NULL
);

CREATE TABLE loyalty_transactions (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id   BIGINT NOT NULL REFERENCES customers(id),
  txn_type      TEXT NOT NULL CHECK (txn_type IN ('earn','redeem','bonus','expire','adjust')),
  points        INTEGER NOT NULL,                  -- negative for redeem / expire
  order_id      BIGINT REFERENCES orders(id),
  description   TEXT,
  expires_on    TEXT,
  created_at    TIMESTAMPTZ NOT NULL
);

CREATE TABLE rewards_catalog (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name_th        TEXT NOT NULL,
  name_en        TEXT,
  reward_type    TEXT NOT NULL CHECK (reward_type IN ('discount_coupon','free_product','free_shipping','experience')),
  points_cost    INTEGER NOT NULL,
  variant_id     BIGINT REFERENCES product_variants(id),
  discount_value NUMERIC(10,2),
  min_tier_id    BIGINT REFERENCES loyalty_tiers(id),
  is_active      BOOLEAN NOT NULL DEFAULT TRUE,
  origin         TEXT NOT NULL CHECK (origin IN ('official','assumed_for_demo'))
);

CREATE TABLE reward_redemptions (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id   BIGINT NOT NULL REFERENCES customers(id),
  reward_id     BIGINT NOT NULL REFERENCES rewards_catalog(id),
  points_spent  INTEGER NOT NULL,
  coupon_id     BIGINT REFERENCES coupons(id),
  redeemed_at   TIMESTAMPTZ NOT NULL
);

-- ───────────────────────────── 6. ADVISOR SESSIONS (mock; PDPA-aware design) ─────────────────────────────
CREATE TABLE consent_records (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id      BIGINT NOT NULL REFERENCES customers(id),
  consent_type     TEXT NOT NULL CHECK (consent_type IN ('rewards_terms','face_photo_analysis','skin_profile_storage','marketing','cross_border_processing')),
  policy_version   TEXT NOT NULL,
  consent_text_th  TEXT NOT NULL,                  -- the exact wording the customer agreed to
  granted_at       TIMESTAMPTZ NOT NULL,
  withdrawn_at     TIMESTAMPTZ,
  channel          TEXT NOT NULL DEFAULT 'line_oa',
  is_minor_flow    BOOLEAN NOT NULL DEFAULT FALSE  -- guardian consent path used
);

CREATE TABLE customer_skin_profiles (              -- what the customer TOLD us (a photo cannot reveal it)
  customer_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY REFERENCES customers(id),
  consent_id          BIGINT NOT NULL REFERENCES consent_records(id),
  self_reported_skin_type_id BIGINT REFERENCES skin_types(id),
  sensitivity_level   TEXT CHECK (sensitivity_level IN ('low','medium','high') OR sensitivity_level IS NULL),
  known_reactions     TEXT,
  goals               JSONB,                        -- ranked concern slugs
  current_routine     TEXT,
  routine_appetite    TEXT CHECK (routine_appetite IN ('minimal_3_steps','standard_5_steps','full_layering') OR routine_appetite IS NULL),
  budget_per_product  NUMERIC(10,2),
  wears_makeup        TEXT CHECK (wears_makeup IN ('never','sometimes','daily') OR wears_makeup IS NULL),
  environment         TEXT,
  is_pregnant_or_nursing BOOLEAN,
  updated_at          TIMESTAMPTZ NOT NULL
);

CREATE TABLE face_analysis_sessions (
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id        BIGINT NOT NULL REFERENCES customers(id),
  consent_id         BIGINT NOT NULL REFERENCES consent_records(id),
  image_ref          TEXT,                         -- opaque object-store key; the image itself is NEVER stored in the DB
  image_sha256       TEXT,
  image_count        INTEGER NOT NULL DEFAULT 1,
  image_expires_at   TIMESTAMPTZ NOT NULL,           -- retention deadline
  image_deleted_at   TIMESTAMPTZ,
  photo_quality      TEXT CHECK (photo_quality IN ('good','usable','poor')),
  quality_flags      JSONB,                         -- ['beauty_filter_suspected','low_light','makeup_on']
  model_version      TEXT NOT NULL,
  observed_skin_type_id BIGINT REFERENCES skin_types(id),
  observed_undertone TEXT,
  observed_depth     TEXT,
  summary_th         TEXT,
  status             TEXT NOT NULL CHECK (status IN ('completed','rejected_quality','consent_withdrawn')),
  created_at         TIMESTAMPTZ NOT NULL
);

CREATE TABLE analysis_findings (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id   BIGINT NOT NULL REFERENCES face_analysis_sessions(id),
  concern_id   BIGINT NOT NULL REFERENCES skin_concerns(id),
  face_zone    TEXT NOT NULL CHECK (face_zone IN ('forehead','nose','t_zone','cheeks','under_eye','chin_jaw','lips','overall')),
  severity     INTEGER NOT NULL CHECK (severity BETWEEN 0 AND 4),
  confidence   TEXT NOT NULL CHECK (confidence IN ('high','medium','low')),
  observation_en TEXT
);

CREATE TABLE recommendations (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id     BIGINT NOT NULL REFERENCES face_analysis_sessions(id),
  product_id     BIGINT NOT NULL REFERENCES products(id),
  variant_id     BIGINT REFERENCES product_variants(id),   -- set when a shade / size was matched
  step_id        BIGINT REFERENCES routine_steps(id),
  rank           INTEGER NOT NULL,
  reason_en      TEXT NOT NULL,
  reason_th      TEXT,
  addresses_concern_id BIGINT REFERENCES skin_concerns(id),
  outcome        TEXT CHECK (outcome IN ('shown','added_to_cart','purchased','dismissed') OR outcome IS NULL)
);

CREATE TABLE routines (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id  BIGINT NOT NULL REFERENCES customers(id),
  session_id   BIGINT REFERENCES face_analysis_sessions(id),
  name         TEXT NOT NULL,
  goal_en      TEXT,
  is_active    BOOLEAN NOT NULL DEFAULT TRUE,
  review_after TEXT,                               -- date to check in with the customer
  created_at   TIMESTAMPTZ NOT NULL
);

CREATE TABLE routine_items (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  routine_id    BIGINT NOT NULL REFERENCES routines(id),
  period        TEXT NOT NULL CHECK (period IN ('am','pm')),
  step_id       BIGINT NOT NULL REFERENCES routine_steps(id),
  product_id    BIGINT REFERENCES products(id),   -- NULL when the slot is a range gap
  gap_id        BIGINT REFERENCES range_gaps(id),
  frequency_en  TEXT NOT NULL,
  instruction_en TEXT,
  instruction_th TEXT
);

CREATE TABLE range_gap_events (                    -- R&D demand signal generated as a by-product of advice
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  gap_id        BIGINT NOT NULL REFERENCES range_gaps(id),
  customer_id   BIGINT REFERENCES customers(id),
  session_id    BIGINT REFERENCES face_analysis_sessions(id),
  concern_id    BIGINT REFERENCES skin_concerns(id),
  customer_age_band TEXT,
  customer_skin_type_id BIGINT REFERENCES skin_types(id),
  generic_option_mentioned BOOLEAN NOT NULL DEFAULT TRUE,
  created_at    TIMESTAMPTZ NOT NULL
);

-- ───────────────────────────── 7. VIEWS (what the agent tools read) ─────────────────────────────
CREATE VIEW v_variant_catalog AS
SELECT v.id AS variant_id, v.sku, p.id AS product_id, b.name_en AS brand, l.name_en AS line,
       c.name_en AS category, p.name_en, p.name_th, p.product_type, p.lifecycle_status,
       v.variant_label, v.pack_format, v.size_value, v.size_unit, v.shade_code, v.shade_name,
       v.list_price, v.sale_price, COALESCE(v.sale_price, v.list_price) AS current_price,
       v.web_in_stock, v.is_listed_on_site, p.official_url, p.image_url
FROM product_variants v
JOIN products p ON p.id = v.product_id
JOIN brands b ON b.id = p.brand_id
LEFT JOIN product_lines l ON l.id = p.line_id
LEFT JOIN categories c ON c.id = p.category_id;

CREATE VIEW v_stock_available AS
SELECT i.variant_id, SUM(i.qty_on_hand - i.qty_reserved) AS qty_available,
       SUM(CASE WHEN w.serves = 'online_orders' THEN i.qty_on_hand - i.qty_reserved ELSE 0 END) AS qty_available_online
FROM inventory i JOIN warehouses w ON w.id = i.warehouse_id
GROUP BY i.variant_id;

CREATE VIEW v_gap_demand AS
SELECT g.slug AS gap, g.title_en, g.severity, COUNT(e.id) AS events,
       COUNT(DISTINCT e.customer_id) AS distinct_customers, MIN(e.created_at) AS first_seen, MAX(e.created_at) AS last_seen
FROM range_gaps g LEFT JOIN range_gap_events e ON e.gap_id = g.id
GROUP BY g.id, g.slug, g.title_en, g.severity;

CREATE VIEW v_customer_360 AS
SELECT cu.id AS customer_id, cu.line_user_id, cu.line_display_name, cu.first_name, t.name AS tier,
       la.points_balance, la.spend_this_period,
       (SELECT COUNT(*) FROM orders o WHERE o.customer_id = cu.id AND o.status NOT IN ('cancelled','refunded')) AS order_count,
       (SELECT MAX(o.placed_at) FROM orders o WHERE o.customer_id = cu.id) AS last_order_at,
       (SELECT MAX(s.created_at) FROM face_analysis_sessions s WHERE s.customer_id = cu.id) AS last_analysis_at
FROM customers cu
LEFT JOIN loyalty_accounts la ON la.customer_id = cu.id
LEFT JOIN loyalty_tiers t ON t.id = la.tier_id;
