#!/usr/bin/env python3
"""Step 6 — generate docs/data-dictionary.md and docs/erd.md from db/schema.sql + provenance + live row counts."""
import json, re, sqlite3
from pathlib import Path
ROOT = Path(__file__).resolve().parent.parent
schema = (ROOT / "db/schema.sql").read_text()
prov = {p["table_name"]: p for p in json.load(open(ROOT / "db/seed/data_provenance.json"))}
con = sqlite3.connect(ROOT / "db/srichand.db")
SECTIONS = [("0. Meta", ["data_sources", "data_provenance"]),
            ("1. Catalogue (real, sourced)", ["brands", "product_lines", "categories", "products", "product_variants", "bundle_components", "site_listings", "product_images", "product_claims"]),
            ("2. Ingredients", ["ingredients", "product_ingredients", "product_hero_ingredients", "ingredient_interactions"]),
            ("3. Advisor knowledge (curated)", ["skin_types", "skin_concerns", "product_concerns", "product_skin_types", "routine_steps", "product_routine_steps", "range_gaps", "range_gap_concerns"]),
            ("4. Commerce (mock)", ["warehouses", "inventory", "inventory_movements", "customers", "customer_addresses", "promotions", "promotion_variants", "coupons", "carts", "cart_items", "orders", "order_items", "payments", "shipments", "shipment_events"]),
            ("5. Loyalty — Srichand Rewards", ["loyalty_tiers", "loyalty_accounts", "loyalty_transactions", "rewards_catalog", "reward_redemptions"]),
            ("6. Advisor sessions (mock, PDPA-aware)", ["consent_records", "customer_skin_profiles", "face_analysis_sessions", "analysis_findings", "recommendations", "routines", "routine_items", "range_gap_events"])]
BADGE = {"real_sourced": "🟢 REAL (sourced)", "derived": "🟡 DERIVED from real data", "curated_knowledge": "🔵 CURATED knowledge", "mock": "⚪ MOCK (simulated)"}
tables = {}
for m in re.finditer(r"CREATE TABLE (\w+) \((.*?)\n\);", schema, re.S):
    cols = []
    for ln in m.group(2).split("\n"):
        ln = ln.rstrip()
        mm = re.match(r"^\s+(\w+)\s+([A-Z]+(?:\(\d+,\d+\))?)(.*?)(?:--\s*(.*))?$", ln)
        if not mm or mm.group(1) in ("PRIMARY", "FOREIGN", "CHECK", "UNIQUE"):
            continue
        name, typ, rest, comment = mm.groups()
        fk = re.search(r"REFERENCES (\w+)\((\w+)\)", rest)
        chk = re.search(r"CHECK \(\w+ IN \(([^)]*)\)", rest)
        notes = []
        if "PRIMARY KEY" in rest: notes.append("PK")
        if fk: notes.append(f"→ {fk.group(1)}.{fk.group(2)}")
        if "NOT NULL" in rest: notes.append("required")
        if "UNIQUE" in rest: notes.append("unique")
        if chk: notes.append("one of: " + chk.group(1).replace("'", ""))
        cols.append((name, typ, "; ".join(notes), (comment or "").strip(), fk.group(1) if fk else None))
    tables[m.group(1)] = cols

out = ["# Data dictionary", "", "Generated by `scripts/06_docs.py` from `db/schema.sql`, the provenance registry and the built database. Do not edit by hand.", "",
       "**Legend** — 🟢 REAL: copied from an official or cited source · 🟡 DERIVED: computed from real data by a documented rule · 🔵 CURATED: Bricks knowledge layer · ⚪ MOCK: simulated, to be replaced by the client system named under *Production source*.", ""]
out += ["| Origin | Tables | Rows |", "|---|---|---|"]
for k, label in BADGE.items():
    ts = [t for t in tables if prov.get(t, {}).get("origin") == k]
    out.append(f"| {label} | {len(ts)} | {sum(con.execute(f'SELECT COUNT(*) FROM {t}').fetchone()[0] for t in ts):,} |")
out.append("")
for title, names in SECTIONS:
    out += [f"## {title}", ""]
    for t in names:
        n = con.execute(f"SELECT COUNT(*) FROM {t}").fetchone()[0]
        p = prov[t]
        out += [f"### `{t}` — {n:,} rows", "", f"{BADGE[p['origin']]} — {p['description']}" + (f"  \n*Production source:* {p['production_source']}" if p["production_source"] else ""), "",
                "| Column | Type | Constraints | Notes |", "|---|---|---|---|"]
        out += [f"| `{c[0]}` | {c[1]} | {c[2]} | {c[3]} |" for c in tables[t]]
        out.append("")
out += ["## 7. Views", "", "| View | Purpose |", "|---|---|",
        "| `v_variant_catalog` | One row per SKU with brand, line, category, current price and web stock — what search and cart tools read |",
        "| `v_stock_available` | On-hand minus reserved, total and for online-order warehouses |",
        "| `v_gap_demand` | Range-gap events per gap: count, distinct customers, first/last seen — the R&D signal |",
        "| `v_customer_360` | Customer with tier, points, order count, last order, last analysis |", ""]
out += ["## Derivation rules (the 🟡 fields)", "",
        "| Field | Rule |", "|---|---|",
        "| `products` rows | 345 site listings are classified by name prefix (`[Clearance]`, `[Bogo]`, `[N ชิ้น]`, `ฟรี`, `(1 กล่อง)`, set keywords) and grouped by a normalised Thai name key; 40 hand overrides are listed at the top of `scripts/01_build_catalog.py`. Clearance lots are fuzzy-matched to canonical products by English name (≥ 0.80) or mapped by hand. |",
        "| `products.name_en` | From the official URL slug, with hand corrections. The official site is Thai-only. |",
        "| `products.summary_en` | Bricks' English summary of official Thai copy + INCI facts, for 33 core products. |",
        "| `finish`, `coverage`, `oil_control_hours_claimed`, `is_water_resistant_claimed`, `tested_claims_th` | Regex over official Thai copy (e.g. `คุมมัน 14 ชั่วโมง` → 14). |",
        "| `is_fragrance_free`, `is_alcohol_free` | From the INCI list when one exists (fact), else from the official free-from line, else NULL. |",
        "| `product_variants.pack_format` | `sachet_box` = listing sold as a box of 6 sachets; `multipack` = `[N ชิ้น]` / twin pack / BOGO; `mini` = ≤ 20 ml/g and at most half the largest size. |",
        "| `shade_undertone` | From official shade names/prefixes: Pinkish or `P##` → cool_pink; `N##` → neutral; `Y##` → warm_yellow; Honey/Golden → warm_golden; Peach → peach; else NULL. |",
        "| `shade_depth_rank` | Rank of the numeric shade code within the product (105 < 110 < …). |",
        "| `bundle_components` | Canonical product names found in the set's official name/description. Quantities only when printed in the listing name. |",
        "| `promotions` (observed) | Sale prices, BOGO listings, ฿499 gift (verified in a live cart), September coupon tiers. Coupon code strings are placeholders. |", ""]
(ROOT / "docs/data-dictionary.md").write_text("\n".join(out))

erd = ["# Entity-relationship diagram", "", "Generated from `db/schema.sql`. Rendered by GitHub, VS Code (Mermaid preview) or https://mermaid.live.", ""]
for title, names in SECTIONS[1:]:
    erd += [f"## {title}", "", "```mermaid", "erDiagram"]
    shown = set(names)
    for t in names:
        for c in tables[t]:
            if c[4]:
                shown.add(c[4])
                erd.append(f"  {c[4]} ||--o{{ {t} : \"{c[0]}\"")
    for t in sorted(shown):
        erd.append(f"  {t} {{")
        for c in tables[t][:7]:
            erd.append(f"    {c[1].split('(')[0].lower()} {c[0]}" + (" PK" if "PK" in c[2] else " FK" if c[4] else ""))
        erd.append("  }")
    erd += ["```", ""]
(ROOT / "docs/erd.md").write_text("\n".join(erd))
print("docs written:", len(tables), "tables")
