"""Curated advisor knowledge. Everything here is either
  (a) general cosmetic-science knowledge (ingredient dictionary, concerns, routine steps), or
  (b) a reading of OFFICIAL srichand.com copy for a product (hero ingredients, positioning).
No product fact is invented: hero ingredients are only those the brand itself names."""

SKIN_TYPES = [
    ("oily", "Oily", "ผิวมัน", "Visible shine across the face within a few hours of cleansing; larger-looking pores."),
    ("combination", "Combination", "ผิวผสม", "Oily T-zone with normal-to-dry cheeks."),
    ("normal", "Normal", "ผิวธรรมดา", "Balanced; little shine or tightness."),
    ("dry", "Dry", "ผิวแห้ง", "Tightness, flaking or dull rough patches; little visible oil."),
    ("sensitive", "Sensitive", "ผิวแพ้ง่าย", "Stings, flushes or itches easily with new products or heat."),
    ("acne-prone", "Acne-prone", "ผิวเป็นสิวง่าย", "Breaks out or clogs easily, usually alongside oily or combination skin."),
    ("dehydrated-oily", "Oily but dehydrated", "ผิวมันแต่ขาดน้ำ", "Shiny surface yet feels tight; common in air-conditioned, humid climates."),
]

# slug, en, th, group, photo_detectable, photo cues, Thai-FDA-safe wording, when to refer out
CONCERNS = [
    ("excess-sebum-shine", "Excess oil & shine", "ผิวมัน หน้ามันเงา", "oil_pores", "yes", "Specular shine on forehead, nose, medial cheeks under flash or daylight.", "ช่วยควบคุมความมันส่วนเกิน ผิวแลดูไม่มันเงา", None),
    ("enlarged-pores", "Visible pores", "รูขุมขนกว้าง", "oil_pores", "yes", "Pore openings visible on nose / medial cheeks in raking light.", "ช่วยให้รูขุมขนแลดูกระชับ เบลอรูขุมขน", None),
    ("blackheads-congestion", "Blackheads & congestion", "สิวเสี้ยน สิวอุดตัน", "oil_pores", "partly", "Dark dots on nose/chin; small closed bumps on forehead in raking light.", "ช่วยทำความสะอาดรูขุมขน ผิวแลดูเรียบเนียนขึ้น", None),
    ("acne-breakouts", "Breakouts", "สิว", "acne", "yes", "Inflamed papules / pustules; count and distribution.", "สูตรสำหรับผิวเป็นสิว / เหมาะสำหรับผิวที่มีแนวโน้มเป็นสิว (ห้ามใช้คำว่า รักษา ลด หรือป้องกันสิว)", "Many inflamed, painful or cystic lesions, scarring, or no improvement after 8–12 weeks → dermatologist."),
    ("post-acne-marks", "Post-blemish marks", "รอยดำ รอยแดงจากสิว", "acne", "yes", "Flat brown or red macules where blemishes have healed.", "ช่วยให้รอยดำจากสิวแลดูจางลง", None),
    ("dark-spots-sun", "Dark spots & sun spots", "จุดด่างดำ จุดดำแดด", "pigment", "yes", "Discrete flat brown spots on cheeks / temples.", "ช่วยให้จุดด่างดำแลดูจางลง", "A spot that changes shape/colour, bleeds or is raised → doctor."),
    ("melasma", "Melasma-type patches", "ฝ้า", "pigment", "partly", "Symmetric brown patches on cheeks, forehead, upper lip. Cannot be confirmed from a photo.", "ช่วยให้จุดด่างดำแลดูจางลง ผิวแลดูกระจ่างใสสม่ำเสมอ (ผลลัพธ์ขึ้นอยู่กับแต่ละบุคคล; ห้ามอ้างว่ารักษาหรือลดฝ้า)", "Melasma is a medical diagnosis; persistent or spreading patches → dermatologist."),
    ("dullness-uneven-tone", "Dullness & uneven tone", "ผิวหมองคล้ำ สีผิวไม่สม่ำเสมอ", "pigment", "yes", "Low luminosity, patchy tone differences between zones.", "ช่วยให้ผิวแลดูกระจ่างใส สีผิวแลดูสม่ำเสมอ", None),
    ("under-eye-darkness", "Under-eye darkness", "ใต้ตาคล้ำ", "pigment", "partly", "Brown (pigment), blue-purple (vascular) or shadow (structural) under-eye tone.", "ช่วยปกปิดรอยคล้ำใต้ตา", None),
    ("fine-lines-wrinkles", "Fine lines & wrinkles", "ริ้วรอย", "ageing", "yes", "Static lines at forehead, crow's feet, nasolabial area at rest.", "ช่วยให้ริ้วรอยแลดูลดเลือน", None),
    ("loss-of-firmness", "Loss of firmness", "ผิวหย่อนคล้อย ไม่กระชับ", "ageing", "partly", "Jawline definition, mid-face descent; heavily pose-dependent.", "ช่วยให้ผิวแลดูกระชับ", None),
    ("rough-texture", "Rough or uneven texture", "ผิวไม่เรียบเนียน", "ageing", "yes", "Surface irregularity in raking light.", "ช่วยให้ผิวแลดูเรียบเนียน", None),
    ("dehydration", "Dehydration", "ผิวขาดน้ำ", "hydration_barrier", "partly", "Fine crepey lines, dull surface that still shows oil.", "เติมความชุ่มชื้น ผิวแลดูอิ่มน้ำ", None),
    ("dryness", "Dryness & flaking", "ผิวแห้ง ลอกเป็นขุย", "hydration_barrier", "yes", "Visible flaking, rough matte patches.", "ให้ความชุ่มชื้น ลดความแห้งกร้าน", None),
    ("compromised-barrier", "Weakened skin barrier", "ปราการผิวอ่อนแอ", "hydration_barrier", "no", "Not reliably visible; inferred from stinging, tightness and history of over-exfoliation.", "เสริมปราการผิวให้แลดูแข็งแรง", None),
    ("sensitivity-redness", "Sensitivity & redness", "ผิวแพ้ง่าย ผิวแดง", "sensitivity", "partly", "Diffuse erythema on cheeks/nose. Reactivity itself is invisible — ask.", "ปลอบประโลมผิว เหมาะสำหรับผิวแพ้ง่าย", "Persistent facial redness with bumps or visible vessels may be rosacea → dermatologist."),
    ("daily-uv-protection", "Daily UV protection", "ปกป้องผิวจากแสงแดด", "sun", "no", "Everyone needs it; photo only shows accumulated damage.", "ปกป้องผิวจากรังสี UVA/UVB", None),
    ("makeup-longevity-oil-control", "Makeup that survives heat & oil", "เมคอัพติดทน คุมมัน", "makeup_goal", "no", "Ask about midday shine and makeup breakdown.", "คุมมัน ติดทน", None),
    ("coverage-blemishes", "Covering blemishes & marks", "ปกปิดรอยสิว จุดด่างดำ", "makeup_goal", "no", "Goal-based; ask.", "ช่วยปกปิดจุดบกพร่อง ผิวแลดูเรียบเนียน", None),
    ("natural-everyday-base", "Natural everyday base", "งานผิวธรรมชาติ", "makeup_goal", "no", "Goal-based; ask.", "งานผิวบางเบาเป็นธรรมชาติ", None),
    ("lip-dryness", "Dry lips", "ริมฝีปากแห้ง", "makeup_goal", "partly", "Visible flaking or lines on lips.", "บำรุงริมฝีปากให้ชุ่มชื้น", None),
]

# slug, en, th, order, am, pm, is_makeup
ROUTINE_STEPS = [
    ("makeup-removal", "Remove makeup & sunscreen", "เช็ดเครื่องสำอาง", 10, 0, 1, 0),
    ("cleanse", "Cleanse", "ล้างหน้า", 20, 1, 1, 0),
    ("toner-pad", "Toner pad / exfoliate", "โทนเนอร์แพด / ผลัดเซลล์ผิว", 30, 0, 1, 0),
    ("essence", "Essence", "น้ำตบ / เอสเซนส์", 40, 1, 1, 0),
    ("treatment-serum", "Treatment serum", "เซรั่มบำรุงเฉพาะจุดประสงค์", 50, 1, 1, 0),
    ("moisturise", "Moisturise", "มอยส์เจอร์ไรเซอร์", 60, 1, 1, 0),
    ("mask", "Mask (1–3× weekly)", "มาส์ก", 65, 0, 1, 0),
    ("sunscreen", "Sunscreen", "กันแดด", 70, 1, 0, 0),
    ("primer", "Primer", "ไพรเมอร์", 80, 1, 0, 1),
    ("base", "Foundation / cushion", "รองพื้น / คุชชั่น", 90, 1, 0, 1),
    ("conceal", "Conceal", "คอนซีลเลอร์", 100, 1, 0, 1),
    ("powder", "Set with powder", "แป้ง", 110, 1, 0, 1),
    ("colour", "Cheeks, eyes & brows", "บลัช ตา คิ้ว", 120, 1, 0, 1),
    ("lips", "Lip colour", "ลิป", 130, 1, 0, 1),
    ("setting-spray", "Setting spray", "สเปรย์ล็อกเมคอัพ", 140, 1, 0, 1),
    ("lip-care", "Lip care", "บำรุงริมฝีปาก", 150, 1, 1, 0),
]

# inci, common, th, class, what it does (cosmetic language), evidence, caution, is_uv, uv_cov, irritant, fragrance
INGREDIENTS = [
    ("Niacinamide", "Vitamin B3", "ไนอะซินาไมด์ (วิตามินบี 3)", "brightener", "Helps skin look more even and refined, supports the barrier and helps regulate the look of oil.", "strong", "Above ~5% a minority of people flush or sting.", 0, None, 0, 0),
    ("Salicylic Acid", "BHA", "ซาลิไซลิก แอซิด (บีเอชเอ)", "bha", "Oil-soluble exfoliant that works inside the pore lining; the classic ingredient for congestion and blackheads.", "strong", "Can dry or irritate; avoid stacking with other exfoliants; not for aspirin allergy.", 0, None, 1, 0),
    ("Glycolic Acid", "AHA", "ไกลโคลิก แอซิด (เอเอชเอ)", "aha", "Water-soluble exfoliant that loosens dull surface cells for a smoother, brighter look.", "strong", "Raises sun sensitivity — sunscreen is mandatory. Do not combine with a retinoid in the same session.", 0, None, 1, 0),
    ("Hydroxypinacolone Retinoate", "HPR / Granactive Retinoid", "ไฮดรอกซีพินาโคโลน เรติโนเอต", "retinoid", "A retinoic-acid ester that acts on skin's retinoid receptors without conversion steps; smooths the look of lines and texture with less irritation than retinol.", "moderate", "Introduce 2–3 nights a week; PM only; daily sunscreen; avoid in pregnancy.", 0, None, 1, 0),
    ("Retinyl Palmitate", "Vitamin A ester", "เรตินิล พาลมิเตต", "retinoid", "Mild vitamin-A ester; gentle support for the look of texture.", "emerging", "Avoid in pregnancy.", 0, None, 0, 0),
    ("Bakuchiol", "Plant retinol-alternative", "บาคูชิออล", "retinoid_alternative", "Plant-derived antioxidant studied as a gentler alternative to retinol for the look of lines and tone.", "moderate", None, 0, None, 0, 0),
    ("Tranexamic Acid", "TXA", "ทรานซามิก แอซิด", "brightener", "Helps stubborn dark patches and post-blemish marks look lighter.", "moderate", None, 0, None, 0, 0),
    ("Alpha-Arbutin", "Alpha arbutin", "อัลฟ่า อาร์บูติน", "brightener", "Helps dark spots look lighter by slowing visible pigment formation.", "moderate", None, 0, None, 0, 0),
    ("Sodium Ascorbyl Phosphate", "Vitamin C derivative (SAP)", "โซเดียม แอสคอร์บิล ฟอสเฟต", "vitamin_c", "Stable vitamin-C derivative; antioxidant, supports a brighter look.", "moderate", None, 0, None, 0, 0),
    ("Ascorbyl Glucoside", "Vitamin C derivative", "แอสคอร์บิล กลูโคไซด์", "vitamin_c", "Stable vitamin-C derivative for a brighter, more even look.", "moderate", None, 0, None, 0, 0),
    ("Ascorbic Acid", "Pure vitamin C", "วิตามินซีบริสุทธิ์", "vitamin_c", "Benchmark antioxidant for brightness; unstable unless formulated at low pH.", "strong", "Can sting at high strength.", 0, None, 1, 0),
    ("3-O-Ethyl Ascorbic Acid", "Ethyl vitamin C", "เอทิล แอสคอร์บิก แอซิด", "vitamin_c", "Stable, well-penetrating vitamin-C derivative.", "moderate", None, 0, None, 0, 0),
    ("Hippophae Rhamnoides Fruit Extract", "Sea buckthorn", "สารสกัดซีบัคธอร์น", "antioxidant", "Antioxidant-rich fruit extract; the 'super fruit' of the Super C line.", "cosmetic_only", None, 0, None, 0, 0),
    ("Sodium DNA", "PDRN (plant-derived in this range)", "พีดีอาร์เอ็น", "skin_conditioning", "Conditioning ingredient positioned for glow and a firmer look; Srichand extracts it from camellia flowers.", "emerging", None, 0, None, 0, 0),
    ("Camellia Japonica Flower Extract", "Camellia extract", "สารสกัดดอกคามิลเลีย", "antioxidant", "Antioxidant flower extract.", "cosmetic_only", None, 0, None, 0, 0),
    ("Ectoin", "Ectoin", "เอคโตอิน", "soothing", "Stress-protection molecule that helps calm skin and hold water.", "moderate", None, 0, None, 0, 0),
    ("Panthenol", "Pro-vitamin B5", "แพนทีนอล (วิตามินบี 5)", "soothing", "Humectant that soothes and supports barrier recovery.", "strong", None, 0, None, 0, 0),
    ("Dipotassium Glycyrrhizate", "Licorice-derived soother", "ไดโพแทสเซียม ไกลซีไรเซต", "soothing", "Calms the look of redness.", "moderate", None, 0, None, 0, 0),
    ("Centella Asiatica Extract", "Cica", "สารสกัดใบบัวบก", "soothing", "Soothing botanical widely used for stressed or blemish-prone skin.", "moderate", None, 0, None, 0, 0),
    ("Madecassoside", "Cica active", "มาเดคาสโซไซด์", "soothing", "Purified centella compound; soothing.", "moderate", None, 0, None, 0, 0),
    ("Castanea Sativa (Chestnut) Leaf Extract", "Chestnut leaf extract (Derma-calmfort)", "สารสกัดใบเกาลัด", "soothing", "Named by Srichand as a hydration and barrier-support active.", "cosmetic_only", None, 0, None, 0, 0),
    ("Allantoin", "Allantoin", "อัลลันโทอิน", "soothing", "Classic skin soother.", "moderate", None, 0, None, 0, 0),
    ("Bisabolol", "Bisabolol", "บิซาโบลอล", "soothing", "Chamomile-derived soother.", "moderate", None, 0, None, 0, 0),
    ("Glyceryl Glucoside", "Glyceryl glucoside", "กลีเซอริล กลูโคไซด์", "humectant", "Humectant linked to skin's own water channels (aquaporin-3); helps skin hold water.", "moderate", None, 0, None, 0, 0),
    ("Sodium Hyaluronate", "Hyaluronic acid (salt)", "ไฮยาลูรอนิก แอซิด", "humectant", "Binds water at the surface for a plumper look.", "strong", None, 0, None, 0, 0),
    ("Hyaluronic Acid", "Hyaluronic acid", "ไฮยาลูรอนิก แอซิด", "humectant", "Binds water at the surface for a plumper look.", "strong", None, 0, None, 0, 0),
    ("Trehalose", "Trehalose", "ทรีฮาโลส", "humectant", "Sugar humectant that helps lock in water.", "moderate", None, 0, None, 0, 0),
    ("Betaine", "Betaine", "เบทาอีน", "humectant", "Plant-derived osmolyte; light, non-sticky hydration.", "moderate", None, 0, None, 0, 0),
    ("Glycerin", "Glycerin", "กลีเซอรีน", "humectant", "Workhorse humectant.", "strong", None, 0, None, 0, 0),
    ("Ceramide NP", "Ceramide", "เซราไมด์", "ceramide", "Barrier lipid; helps reduce water loss.", "strong", None, 0, None, 0, 0),
    ("Ceramide AP", "Ceramide", "เซราไมด์", "ceramide", "Barrier lipid.", "strong", None, 0, None, 0, 0),
    ("Ceramide EOP", "Ceramide", "เซราไมด์", "ceramide", "Barrier lipid.", "strong", None, 0, None, 0, 0),
    ("Cholesterol", "Cholesterol", "คอเลสเตอรอล", "ceramide", "Barrier lipid that works with ceramides.", "strong", None, 0, None, 0, 0),
    ("Phytosphingosine", "Phytosphingosine", "ไฟโตสฟิงโกซีน", "ceramide", "Ceramide precursor; barrier support.", "moderate", None, 0, None, 0, 0),
    ("Acetyl Hexapeptide-8", "Peptide", "เปปไทด์", "peptide", "Signal peptide used for the look of expression lines.", "emerging", None, 0, None, 0, 0),
    ("Palmitoyl Tetrapeptide-10", "Peptide", "เปปไทด์", "peptide", "Peptide positioned for a smoother, more luminous look.", "emerging", None, 0, None, 0, 0),
    ("Hamamelis Virginiana (Witch Hazel) Extract", "Witch hazel", "สารสกัดวิชฮาเซล", "astringent", "Tones the look of pores; antioxidant.", "cosmetic_only", "Alcohol-based witch hazel can irritate; extract form is milder.", 0, None, 0, 0),
    ("Melaleuca Alternifolia (Tea Tree) Leaf Oil", "Tea tree oil", "ทีทรีออยล์", "purifying", "Purifying essential oil used in blemish care.", "moderate", "Essential oil — can sensitise.", 0, None, 1, 0),
    ("Zinc PCA", "Zinc PCA", "ซิงค์ พีซีเอ", "sebum_regulating", "Helps regulate the look of oil.", "moderate", None, 0, None, 0, 0),
    ("Calamine", "Calamine", "คาลาไมน์", "absorbent", "Soothing, oil-absorbing mineral; the heart of the 1948 Original Powder Mask.", "moderate", None, 0, None, 0, 0),
    ("Silica", "Silica", "ซิลิกา", "absorbent", "Oil-absorbing, soft-focus powder.", "strong", None, 0, None, 0, 0),
    ("Talc", "Talc", "ทัลค์", "absorbent", "Classic powder base; absorbs oil and gives slip.", "strong", None, 0, None, 0, 0),
    ("Tocopherol", "Vitamin E", "วิตามินอี", "antioxidant", "Antioxidant; supports vitamin C and sunscreen.", "strong", None, 0, None, 0, 0),
    ("Tocopheryl Acetate", "Vitamin E acetate", "วิตามินอี", "antioxidant", "Stable vitamin-E ester.", "moderate", None, 0, None, 0, 0),
    ("Lactobacillus Ferment", "Probiotic ferment", "โพรไบโอติกส์", "skin_conditioning", "Ferment positioned for microbiome-friendly cleansing.", "emerging", None, 0, None, 0, 0),
    ("Acacia Senegal Gum", "Acacia gum ('natural collagen')", "อะคาเซีย เซเนกัล กัม", "film_former", "Gives an instant smoothing, tightening feel.", "cosmetic_only", None, 0, None, 0, 0),
    # UV filters
    ("Bis-Ethylhexyloxyphenol Methoxyphenyl Triazine", "Tinosorb S (bemotrizinol)", "ทิโนซอร์บ เอส", "uv_filter", "Photostable broad-spectrum filter covering UVB and UVA; also stabilises avobenzone.", "strong", None, 1, "UVA+UVB", 0, 0),
    ("Diethylamino Hydroxybenzoyl Hexyl Benzoate", "Uvinul A Plus (DHHB)", "ยูวินูล เอ พลัส", "uv_filter", "Photostable UVA filter with strong UVA1 coverage.", "strong", None, 1, "UVA", 0, 0),
    ("Ethylhexyl Triazone", "Uvinul T150", "เอทิลเฮกซิล ไตรอะโซน", "uv_filter", "Very efficient, photostable UVB filter.", "strong", None, 1, "UVB", 0, 0),
    ("Butyl Methoxydibenzoylmethane", "Avobenzone", "อะโวเบนโซน", "uv_filter", "Global standard UVA filter; needs stabilisers.", "strong", None, 1, "UVA", 0, 0),
    ("Ethylhexyl Salicylate", "Octisalate", "ออคติซาเลต", "uv_filter", "UVB filter and solvent for other filters. (A UV filter — not the exfoliant salicylic acid.)", "strong", None, 1, "UVB", 0, 0),
    ("Ethylhexyl Methoxycinnamate", "Octinoxate", "ออคติน็อกเซต", "uv_filter", "Common UVB filter.", "strong", "Restricted in some reef-protection jurisdictions.", 1, "UVB", 0, 0),
    ("Homosalate", "Homosalate", "โฮโมซาเลต", "uv_filter", "UVB filter.", "strong", None, 1, "UVB", 0, 0),
    ("Octocrylene", "Octocrylene", "ออกโตไครลีน", "uv_filter", "UVB filter; stabilises avobenzone.", "strong", None, 1, "UVB", 0, 0),
    ("Titanium Dioxide", "Titanium dioxide", "ไทเทเนียม ไดออกไซด์", "uv_filter", "Mineral filter (UVB + short UVA); also a white pigment in makeup.", "strong", None, 1, "UVB+UVA2", 0, 0),
    ("Zinc Oxide", "Zinc oxide", "ซิงค์ ออกไซด์", "uv_filter", "Mineral broad-spectrum filter; soothing.", "strong", None, 1, "UVA+UVB", 0, 0),
    ("Methylene Bis-Benzotriazolyl Tetramethylbutylphenol", "Tinosorb M (bisoctrizole)", "ทิโนซอร์บ เอ็ม", "uv_filter", "Hybrid organic-particle broad-spectrum filter.", "strong", None, 1, "UVA+UVB", 0, 0),
    ("Phenylbenzimidazole Sulfonic Acid", "Ensulizole", "เอนซูลิโซล", "uv_filter", "Water-soluble UVB filter; light feel.", "strong", None, 1, "UVB", 0, 0),
    # formula-character flags
    ("Parfum", "Fragrance", "น้ำหอม", "fragrance", "Scent.", None, "Most common cosmetic sensitiser; avoid for reactive skin.", 0, None, 1, 1),
    ("Fragrance", "Fragrance", "น้ำหอม", "fragrance", "Scent.", None, "Most common cosmetic sensitiser; avoid for reactive skin.", 0, None, 1, 1),
    ("Alcohol Denat.", "Denatured alcohol", "แอลกอฮอล์", "solvent", "Fast-drying solvent; lightens texture.", None, "Can be drying for dry or sensitive skin at high levels.", 0, None, 1, 0),
    ("Phenoxyethanol", "Phenoxyethanol", "ฟีน็อกซีเอทานอล", "preservative", "Widely used preservative.", None, None, 0, None, 0, 0),
    ("Dimethicone", "Silicone", "ไดเมทิโคน", "emollient", "Silky, breathable emollient; blurs texture.", "strong", None, 0, None, 0, 0),
    ("Water", "Water", "น้ำ", "solvent", "Base of the formula.", None, None, 0, None, 0, 0),
    ("Butylene Glycol", "Butylene glycol", "บิวทิลีน ไกลคอล", "humectant", "Light humectant and solvent.", "strong", None, 0, None, 0, 0),
    ("Propanediol", "Propanediol", "โพรเพนไดออล", "humectant", "Plant-derived humectant and solvent.", "moderate", None, 0, None, 0, 0),
]
INGREDIENT_ALIASES = {  # normalised label spelling -> dictionary INCI
    "aqua": "Water", "water/aqua": "Water", "aqua/water": "Water", "water (aqua)": "Water", "aqua (water)": "Water",
    "alpha arbutin": "Alpha-Arbutin", "alpha-arbutin": "Alpha-Arbutin", "tocopherol (vitamin e)": "Tocopherol",
    "alcohol denat": "Alcohol Denat.", "alcohol": "Alcohol Denat.", "fragrance (parfum)": "Parfum", "parfum (fragrance)": "Parfum",
    "perfume": "Parfum", "centella asiatica leaf extract": "Centella Asiatica Extract", "centella asiatica extract": "Centella Asiatica Extract",
    "hippophae rhamnoides extract": "Hippophae Rhamnoides Fruit Extract", "hippophae rhamnoides fruit oil": "Hippophae Rhamnoides Fruit Extract",
    "titanium dioxide (ci 77891)": "Titanium Dioxide", "ci 77891": "Titanium Dioxide", "3-o-ethyl ascorbic acid": "3-O-Ethyl Ascorbic Acid",
    "hamamelis virginiana (witch hazel) leaf extract": "Hamamelis Virginiana (Witch Hazel) Extract",
    "hamamelis virginiana (witch hazel) water": "Hamamelis Virginiana (Witch Hazel) Extract",
}

# class_a, class_b, interaction, advice_en, advice_th
INTERACTIONS = [
    ("retinoid", "aha", "avoid_same_session", "Do not layer a retinoid with an exfoliating-strength AHA in the same routine. In this range glycolic acid appears only at low INCI positions (Super C serum #26/36, gel cream #24/29), so the risk is small — but alternate nights if skin feels sensitised.", "ไม่ควรใช้เรตินอยด์ร่วมกับ AHA ความเข้มข้นสูงในรอบเดียวกัน หากผิวระคายเคืองให้สลับคืนกัน"),
    ("retinoid", "bha", "avoid_same_session", "Alternate nights between a retinoid and a BHA toner pad until skin is fully used to both.", "สลับคืนระหว่างเรตินอยด์กับโทนเนอร์แพด BHA"),
    ("aha", "bha", "avoid_same_session", "One exfoliant per session is enough; stacking raises irritation without adding benefit.", "ใช้สารผลัดเซลล์ผิวครั้งละชนิดเดียว"),
    ("retinoid", "retinoid_alternative", "introduce_gradually", "Bakuchiol (Timeless) and HPR (Resurface) can be alternated; start with one, add the other after 4 weeks if wanted.", "เริ่มทีละตัว แล้วค่อยเพิ่มหลัง 4 สัปดาห์"),
    ("retinoid", "uv_filter", "requires_sunscreen", "Any retinoid routine requires daily SPF50+ PA++++ in the morning.", "ใช้เรตินอยด์ต้องทากันแดดทุกเช้า"),
    ("aha", "uv_filter", "requires_sunscreen", "AHAs raise sun sensitivity; daily sunscreen is mandatory.", "ใช้ AHA ต้องทากันแดดทุกวัน"),
    ("bha", "uv_filter", "requires_sunscreen", "Exfoliated skin burns faster; wear sunscreen daily.", "ผิวที่ผลัดเซลล์ไวต่อแดด ควรทากันแดดทุกวัน"),
    ("vitamin_c", "uv_filter", "pairs_well", "Antioxidants under sunscreen improve defence against UV-generated free radicals — use Super C in the morning under Sunlution.", "วิตามินซีใต้กันแดดช่วยเสริมการปกป้องผิว"),
    ("retinoid", "ceramide", "pairs_well", "Buffer a retinoid with a barrier moisturiser (Barrier Boost Soothing Gel Cream) to improve tolerance.", "ใช้คู่กับมอยส์เจอร์ไรเซอร์เสริมปราการผิวเพื่อลดการระคายเคือง"),
    ("retinoid", "soothing", "pairs_well", "Soothing layers (ectoin, panthenol, cica) on retinoid nights reduce dryness.", "สารปลอบประโลมช่วยลดความแห้งในคืนที่ใช้เรตินอยด์"),
    ("brightener", "vitamin_c", "pairs_well", "Niacinamide, tranexamic acid and vitamin-C derivatives work on different steps of visible pigmentation and combine well.", "ไนอะซินาไมด์ ทรานซามิก และวิตามินซี ใช้ร่วมกันได้ดี"),
    ("bha", "soothing", "pairs_well", "Follow BHA with a fragrance-free hydrating layer to offset dryness.", "หลังใช้ BHA ควรตามด้วยผลิตภัณฑ์เติมความชุ่มชื้น"),
]

# ------------------------------------------------------------------ per-product curation (keyed by products.name_en)
# heroes: (name as written by the brand, dictionary INCI or None)
# concerns: (slug, relevance 1-3, basis, rationale)   skin: (slug, suitability, basis)   step: (slug, am, pm, frequency, note)
OP, SC, II = "official_positioning", "site_category", "ingredient_inference"
PRODUCT_CURATION = {
    "Skin Moisture Burst Essence": dict(
        summary="First-step hydrating essence ('น้ำตบ'). Official heroes: glyceryl glucoside, D-panthenol, niacinamide. Claims 72-hour hydration (Dermscan test) and is irritation-tested on sensitive skin; positioned for all skin types, AM and PM.",
        texture="watery essence",
        heroes=[("Glyceryl Glucoside", "Glyceryl Glucoside"), ("D-panthenol", "Panthenol"), ("Niacinamide", "Niacinamide")],
        concerns=[("dehydration", 3, OP, "Core purpose: water-binding first layer."), ("dullness-uneven-tone", 1, II, "Contains niacinamide."), ("compromised-barrier", 1, II, "Panthenol supports barrier comfort.")],
        skin=[("oily", "ideal", II), ("combination", "ideal", OP), ("dehydrated-oily", "ideal", II), ("normal", "ideal", OP), ("dry", "good", OP), ("sensitive", "good", OP)],
        step=("essence", 1, 1, "daily", "Pat into damp skin straight after cleansing.")),
    "Skin Moisture Burst Serum": dict(
        summary="Lightweight hydrating serum. Official heroes: glyceryl glucoside, hyaluronic acid, betaine, witch hazel extract. Claims 72-hour hydration.",
        texture="light serum",
        heroes=[("Glyceryl Glucoside", "Glyceryl Glucoside"), ("Hyaluronic Acid", "Hyaluronic Acid"), ("Betaine", "Betaine"), ("Witch Hazel Extract", "Hamamelis Virginiana (Witch Hazel) Extract")],
        concerns=[("dehydration", 3, OP, "Multi-humectant hydration serum."), ("enlarged-pores", 1, II, "Witch hazel tones the look of pores.")],
        skin=[("oily", "ideal", II), ("combination", "ideal", II), ("dehydrated-oily", "ideal", II), ("normal", "ideal", OP), ("dry", "good", II), ("sensitive", "good", OP)],
        step=("treatment-serum", 1, 1, "daily", "Hydration layer; can sit under any treatment serum.")),
    "Skin Moisture Burst Gel Cream": dict(
        summary="Light gel-cream moisturiser. Official heroes: trehalose, hyaluronic acid, allantoin, apple extract, glyceryl glucoside, centella asiatica, madecassoside, watermelon extract. Claims 72-hour hydration (Dermscan, n=21) and irritation-tested on sensitive skin (n=32). Sold in 50 ml and a 120 ml jumbo.",
        texture="gel-cream",
        heroes=[("Trehalose", "Trehalose"), ("Hyaluronic Acid", "Hyaluronic Acid"), ("Allantoin", "Allantoin"), ("Glyceryl Glucoside", "Glyceryl Glucoside"), ("Centella Asiatica", "Centella Asiatica Extract"), ("Madecassoside", "Madecassoside")],
        concerns=[("dehydration", 3, OP, "Seals in water without heaviness."), ("excess-sebum-shine", 1, II, "Oil-free-feel gel texture suits humid climates."), ("sensitivity-redness", 1, OP, "Cica + allantoin; sensitive-skin tested.")],
        skin=[("oily", "ideal", II), ("combination", "ideal", II), ("dehydrated-oily", "ideal", II), ("normal", "ideal", OP), ("sensitive", "good", OP), ("dry", "caution", II)],
        step=("moisturise", 1, 1, "daily", "Thin layer AM; can be applied thickly as a sleeping mask PM.")),
    "Skin Moisture Burst Bi-Phase Cleansing Water": dict(
        summary="Water-and-oil bi-phase makeup remover for waterproof makeup and sunscreen; 90% natural-origin; safe around eyes and lips per official copy. Fragrance-, alcohol-, paraben- and mineral-oil-free; dermatologist tested.",
        texture="bi-phase liquid",
        heroes=[("11HYA Molecule", "Hyaluronic Acid"), ("Glyceryl Glucoside", "Glyceryl Glucoside"), ("Allantoin & Cucumber", "Allantoin")],
        concerns=[("dehydration", 1, OP, "Removes makeup without the tight feel.")],
        skin=[("normal", "ideal", OP), ("dry", "ideal", II), ("combination", "good", II), ("sensitive", "good", OP), ("oily", "good", II)],
        step=("makeup-removal", 0, 1, "on makeup / water-resistant sunscreen days", "Shake, soak a cotton pad, hold on the eye for 10 seconds before wiping. Follow with a cleanser.")),
    "Skin Moisture Burst 15X Ampoule Mask": dict(
        summary="Jelly-ampoule sheet mask with 15 hydrating actives: glyceryl glucoside, 8 hyaluronic acids, 5 ceramides, trehalose, allantoin, niacinamide.",
        texture="sheet mask",
        heroes=[("Glyceryl Glucoside", "Glyceryl Glucoside"), ("8HYA & 5Ceramide", "Sodium Hyaluronate"), ("Patch20 (Trehalose)", "Trehalose"), ("Allantoin", "Allantoin"), ("Niacinamide PC", "Niacinamide")],
        concerns=[("dehydration", 3, OP, "Intensive hydration boost."), ("compromised-barrier", 2, II, "Ceramides + allantoin.")],
        skin=[("dry", "ideal", II), ("dehydrated-oily", "ideal", II), ("normal", "ideal", II), ("combination", "good", II), ("sensitive", "good", II), ("oily", "good", II)],
        step=("mask", 0, 1, "1–3× weekly", "15–20 minutes after essence; pat in the remainder.")),
    "Barrier Boost Cleansing Gel Foam": dict(
        summary="Gentle gel-to-foam cleanser with ectoin, 'Cicazome' (cica phytosome) and a Lactobacillus ferment (Lacto-encap). Officially irritation-tested on sensitive skin and free of paraben, mineral oil, oil and alcohol. NOTE: the official INCI lists Parfum (#15) and two colourants — unlike the fragrance-free Barrier Boost serum and gel cream — so offer the Phyto Camellia cleanser to customers who react to fragrance.",
        texture="gel-to-foam",
        heroes=[("Ectoin", "Ectoin"), ("Cicazome (Cica-Phytosome)", "Centella Asiatica Extract"), ("Lacto-encap probiotics", "Lactobacillus Ferment")],
        concerns=[("sensitivity-redness", 3, OP, "Built for reactive skin."), ("compromised-barrier", 2, OP, "Non-stripping cleanse.")],
        skin=[("sensitive", "good", OP), ("dry", "ideal", II), ("normal", "ideal", II), ("combination", "good", II), ("oily", "good", II), ("acne-prone", "good", II)],
        step=("cleanse", 1, 1, "daily", "Second cleanse in the evening after makeup removal. Contains fragrance.")),
    "Barrier Boost Essence": dict(
        summary="Soothing, oil-free first-step essence. Heroes: ectoin, Cicazome, chestnut-leaf 'Derma-calmfort', acacia-gum 'natural collagen'. Phyto-Mune complex lists dipotassium glycyrrhizate, chestnut leaf, centella leaf + vesicles. Irritation-tested on sensitive skin (n=32, Dermaproof Asia, Nov 2024).",
        texture="watery essence",
        heroes=[("Ectoin", "Ectoin"), ("Cicazome (Cica-Phytosome)", "Centella Asiatica Extract"), ("Derma-calmfort (Chestnut Leaf Extract)", "Castanea Sativa (Chestnut) Leaf Extract"), ("Natural Collagen (Acacia Senegal Gum)", "Acacia Senegal Gum"), ("Dipotassium Glycyrrhizate", "Dipotassium Glycyrrhizate")],
        concerns=[("sensitivity-redness", 3, OP, "Primary purpose."), ("compromised-barrier", 3, OP, "Barrier-support essence."), ("dehydration", 2, OP, "Hydrating first layer.")],
        skin=[("sensitive", "ideal", OP), ("dry", "ideal", II), ("normal", "ideal", II), ("combination", "good", II), ("oily", "good", OP), ("acne-prone", "good", II)],
        step=("essence", 1, 1, "daily", "Ideal buffer layer on retinoid or exfoliant nights.")),
    "Barrier Boost Serum": dict(
        summary="Fragrance-free barrier serum. Heroes: ectoin, Cicazome, chestnut-leaf extract, Bioglycogen. Free of paraben, mineral oil, silicone, colourant, fragrance, alcohol, sulfate. Irritation-tested on sensitive skin (n=32, Dermaproof Asia, Nov 2024).",
        texture="light serum",
        heroes=[("Ectoin", "Ectoin"), ("Cicazome (Cica-Phytosome)", "Centella Asiatica Extract"), ("Derma-calmfort (Chestnut Leaf Extract)", "Castanea Sativa (Chestnut) Leaf Extract"), ("Bioglycogen", None), ("Dipotassium Glycyrrhizate", "Dipotassium Glycyrrhizate")],
        concerns=[("compromised-barrier", 3, OP, "Primary purpose."), ("sensitivity-redness", 3, OP, "Soothing complex."), ("dehydration", 1, II, "Supports water retention.")],
        skin=[("sensitive", "ideal", OP), ("dry", "ideal", II), ("normal", "ideal", II), ("combination", "good", II), ("oily", "good", II), ("acne-prone", "good", II)],
        step=("treatment-serum", 1, 1, "daily, or as the recovery serum on nights off actives", None)),
    "Barrier Boost Soothing Gel Cream": dict(
        summary="'Jelly Burst Bomb' cooling gel-cream for sensitive skin. Heroes: ectoin, Cicazome, chestnut-leaf extract, Synbiotics Oat (pre + probiotic). Free of paraben, mineral oil, silicone, fragrance, denatured alcohol, sulfate. Irritation-tested on sensitive skin.",
        texture="jelly gel-cream",
        heroes=[("Ectoin", "Ectoin"), ("Cicazome (Cica-Phytosome)", "Centella Asiatica Extract"), ("Derma-calmfort (Chestnut Leaf Extract)", "Castanea Sativa (Chestnut) Leaf Extract"), ("Synbiotics Oat", None)],
        concerns=[("compromised-barrier", 3, OP, "Primary purpose."), ("sensitivity-redness", 3, OP, "Cooling, soothing."), ("dehydration", 2, OP, "Plumps with water.")],
        skin=[("sensitive", "ideal", OP), ("normal", "ideal", II), ("combination", "ideal", II), ("oily", "good", II), ("dry", "good", II), ("acne-prone", "good", II)],
        step=("moisturise", 1, 1, "daily", "Best buffer moisturiser for Resurface nights.")),
    "Phyto Camellia PDRN Bright Glowing Cleansing Gel Foam": dict(
        summary="Pearl gel-to-foam amino-acid cleanser with camellia PDRN, niacinamide, panthenol, vitamin E, 8 hyaluronic acids and a 3-ceramide complex. Full INCI is published on the official page. Irritation-tested for sensitive skin.",
        texture="gel-to-foam",
        heroes=[("Phyto Camellia PDRN", "Sodium DNA"), ("Niacinamide", "Niacinamide"), ("Panthenol", "Panthenol"), ("Hyaluronic acid 8 types & 3 Ceramide complex", "Sodium Hyaluronate")],
        concerns=[("dullness-uneven-tone", 2, OP, "Brightening-positioned cleanse."), ("dehydration", 1, OP, "Non-stripping.")],
        skin=[("normal", "ideal", II), ("combination", "ideal", II), ("oily", "good", II), ("dry", "good", II), ("sensitive", "good", OP)],
        step=("cleanse", 1, 1, "daily", None)),
    "Phyto Camellia PDRN Bright Glowing Essence": dict(
        summary="Glow essence with 0.5% plant (camellia) PDRN, 1.5% niacinamide and 0.1% alpha-arbutin — concentrations are disclosed on the official page. Sugarcane and Irish-moss extracts for hydration. Claims visible glow in 7 days; irritation-tested for sensitive skin.",
        texture="watery essence",
        heroes=[("Phyto Camellia PDRN 0.5%", "Sodium DNA"), ("Niacinamide 1.5%", "Niacinamide"), ("Alpha Arbutin 0.1%", "Alpha-Arbutin")],
        concerns=[("dullness-uneven-tone", 3, OP, "Primary purpose."), ("dehydration", 2, OP, "Hydrating first layer."), ("loss-of-firmness", 1, OP, "Positioned for a firmer look.")],
        skin=[("normal", "ideal", II), ("combination", "ideal", II), ("dry", "good", II), ("oily", "good", II), ("sensitive", "good", OP)],
        step=("essence", 1, 1, "daily", None)),
    "Phyto Camellia PDRN Bright Glowing Serum": dict(
        summary="Glow serum with 0.5% camellia PDRN, 5% niacinamide and 0.1% alpha-arbutin (disclosed), plant collagen amino acids, glyceryl glucoside and dipotassium glycyrrhizate. Irritation-tested for sensitive skin.",
        texture="light serum",
        heroes=[("Phyto Camellia PDRN 0.5%", "Sodium DNA"), ("Niacinamide 5%", "Niacinamide"), ("Alpha Arbutin 0.1%", "Alpha-Arbutin"), ("Glyceryl Glucoside", "Glyceryl Glucoside"), ("Dipotassium Glycyrrhizate", "Dipotassium Glycyrrhizate")],
        concerns=[("dullness-uneven-tone", 3, OP, "Primary purpose."), ("post-acne-marks", 2, II, "5% niacinamide + arbutin."), ("enlarged-pores", 1, II, "5% niacinamide refines the look of pores."), ("loss-of-firmness", 1, OP, "Positioned for a firmer look.")],
        skin=[("normal", "ideal", II), ("combination", "ideal", II), ("oily", "ideal", II), ("dry", "good", II), ("sensitive", "good", OP)],
        step=("treatment-serum", 1, 1, "daily", None)),
    "Phyto Camellia PDRN Bright Glowing Gel Cream": dict(
        summary="Glow gel-cream with 0.5% camellia PDRN, 5% niacinamide, 0.1% alpha-arbutin plus amino acids and peptides. Irritation-tested for sensitive skin.",
        texture="gel-cream",
        heroes=[("Phyto Camellia PDRN 0.5%", "Sodium DNA"), ("Niacinamide 5%", "Niacinamide"), ("Alpha Arbutin 0.1%", "Alpha-Arbutin")],
        concerns=[("dullness-uneven-tone", 3, OP, "Primary purpose."), ("dehydration", 2, OP, "Moisturiser."), ("post-acne-marks", 1, II, "Niacinamide + arbutin.")],
        skin=[("normal", "ideal", II), ("combination", "ideal", II), ("oily", "good", II), ("dry", "good", II), ("sensitive", "good", OP)],
        step=("moisturise", 1, 1, "daily", None)),
    "Super C Brightening Essence": dict(
        summary="Brightening prep essence with liposome vitamin C, sea-buckthorn oil & extract, Korean centella, 8 hyaluronic acids and a 6-ceramide complex. Free of paraben, mineral oil, colourant, alcohol.",
        texture="watery essence",
        heroes=[("Liposome Vitamin C", None), ("Sea Buckthorn Oil & Extract", "Hippophae Rhamnoides Fruit Extract"), ("Centella Asiatica Extract", "Centella Asiatica Extract"), ("8Hya & 6 Ceramide Complex", "Sodium Hyaluronate")],
        concerns=[("dullness-uneven-tone", 3, OP, "Primary purpose."), ("dark-spots-sun", 2, OP, "Positioned for dark spots."), ("dehydration", 1, OP, "Hydrating.")],
        skin=[("normal", "ideal", II), ("combination", "ideal", II), ("oily", "good", II), ("dry", "good", II), ("sensitive", "caution", II)],
        step=("essence", 1, 1, "daily", "AM use under sunscreen gets the most from the antioxidant.")),
    "Super C Brightening Intense Serum": dict(
        summary="Concentrated ampoule-texture brightening serum. Official heroes: vitamin-C derivatives sodium ascorbyl phosphate and ascorbyl glucoside, vitamin B3, tranexamic acid, alpha-arbutin, sea buckthorn. Positioned for sun-induced dark spots; for all skin types. INCI facts: contains Fragrance (#25 of 36); glycolic acid (#26) and the three vitamin-C forms (#29–31, incl. ascorbic acid) sit AFTER the fragrance, i.e. at low levels — niacinamide, tranexamic acid and arbutin carry the formula. Do not describe this serum as an exfoliant.",
        texture="ampoule serum",
        heroes=[("Sodium Ascorbyl Phosphate", "Sodium Ascorbyl Phosphate"), ("Ascorbyl Glucoside", "Ascorbyl Glucoside"), ("Vitamin B3", "Niacinamide"), ("Tranexamic Acid", "Tranexamic Acid"), ("Alpha Arbutin", "Alpha-Arbutin"), ("Sea Buckthorn", "Hippophae Rhamnoides Fruit Extract")],
        concerns=[("dark-spots-sun", 3, OP, "Primary purpose."), ("post-acne-marks", 3, OP, "Official copy names post-acne dark marks."), ("dullness-uneven-tone", 3, OP, "Tone-evening."), ("melasma", 2, OP, "Official copy names melasma/freckle appearance.")],
        skin=[("normal", "ideal", OP), ("combination", "ideal", OP), ("oily", "ideal", OP), ("dry", "good", OP), ("sensitive", "caution", II)],
        step=("treatment-serum", 1, 1, "daily; alternate nights with Resurface", "Best in the morning under sunscreen.")),
    "Super C Brightening Gel Cream": dict(
        summary="Brightening gel-cream: Super C complex with 5% niacinamide + 0.1% alpha-arbutin (disclosed), sea buckthorn, tranexamic acid, centella and glycolic acid. Official copy presents glycolic acid as an exfoliating hero, but it is #24 of 29 on the INCI, so treat any exfoliation as very mild. Fragrance-, silicone-, alcohol-free per official copy.",
        texture="gel-cream",
        heroes=[("Vitamin C Complex", None), ("Niacinamide 5%", "Niacinamide"), ("Alpha-Arbutin 0.1%", "Alpha-Arbutin"), ("Tranexamic Acid", "Tranexamic Acid"), ("Glycolic Acid", "Glycolic Acid"), ("Centella Asiatica", "Centella Asiatica Extract"), ("Seabuckthorn Oil & Extract", "Hippophae Rhamnoides Fruit Extract")],
        concerns=[("dullness-uneven-tone", 3, OP, "Primary purpose."), ("dark-spots-sun", 2, OP, "Positioned for dark spots."), ("post-acne-marks", 2, OP, "Named in official copy."), ("rough-texture", 1, OP, "Contains glycolic acid, but low on the INCI (#24/29): mild at most.")],
        skin=[("normal", "ideal", II), ("combination", "ideal", II), ("oily", "ideal", II), ("dry", "good", II), ("sensitive", "caution", II)],
        step=("moisturise", 1, 1, "daily", "Contains a low level of glycolic acid; if skin is sensitised by Resurface, use a Barrier Boost moisturiser on retinoid nights.")),
    "Super C Brightening 15X Ampoule Mask": dict(
        summary="Jelly-ampoule brightening sheet mask: 'Super Vitamin C', sea buckthorn, niacinamide, tranexamic acid, Melazero (Arisaema amurense extract), alpha-arbutin, 8 hyaluronic acids.",
        texture="sheet mask",
        heroes=[("Super Vitamin C", None), ("Sea Buckthorn Extract", "Hippophae Rhamnoides Fruit Extract"), ("Niacinamide PC", "Niacinamide"), ("Tranexamic Acid", "Tranexamic Acid"), ("Melazero", None), ("Alpha-Arbutin", "Alpha-Arbutin")],
        concerns=[("dullness-uneven-tone", 3, OP, "Brightening boost."), ("dark-spots-sun", 2, OP, "Named in official copy.")],
        skin=[("normal", "ideal", II), ("combination", "ideal", II), ("oily", "good", II), ("dry", "good", II), ("sensitive", "caution", II)],
        step=("mask", 0, 1, "1–3× weekly", None)),
    "Resurface Pro-Retinol Intense Serum": dict(
        summary="The range's retinoid. INCI-verified: Hydroxypinacolone Retinoate (#17), Retinyl Palmitate (#30), niacinamide, ceramides NP/AP/EOP, phytosphingosine, cholesterol, bisabolol, Acetyl Hexapeptide-1 and 13 hyaluronate forms; no fragrance. It does list Alcohol (#23) and BHT. Official hero is Hydroxypinacolone Retinoate (HPR) — described by the brand as a new-generation, stable, fast-acting vitamin A that irritates less than other forms — with peptide technology, 'Hyamide' (hyaluronic acid + ceramide) complex and niacinamide. Free of paraben, mineral oil, colourant and fragrance.",
        texture="serum",
        heroes=[("Hydroxy Pinacolone Retinoate", "Hydroxypinacolone Retinoate"), ("Peptide Technology", None), ("Hyamide Complex (HA + Ceramide)", "Ceramide NP"), ("Niacinamide", "Niacinamide")],
        concerns=[("fine-lines-wrinkles", 3, OP, "Primary purpose."), ("rough-texture", 3, II, "Retinoids are the reference active for texture."), ("loss-of-firmness", 2, OP, "Positioned for a firmer look."), ("enlarged-pores", 2, II, "Retinoids refine the look of pores over time."), ("post-acne-marks", 1, II, "Supports turnover.")],
        skin=[("normal", "ideal", II), ("combination", "ideal", II), ("oily", "ideal", II), ("dry", "good", II), ("sensitive", "caution", II)],
        step=("treatment-serum", 0, 1, "2–3 nights/week for 2 weeks, then every other night, then nightly if comfortable", "PM only. Skip AHA/BHA on the same night. Daily sunscreen. Not for use in pregnancy.")),
    "Timeless Anti-Aging Facial Serum": dict(
        summary="Bakuchiol-based anti-ageing serum — the brand positions bakuchiol as a gentle natural alternative to retinol — with peptide, hyaluronic acid ('Hyalufiller Drone Technology') and niacinamide. Claims a firmer look in 3 days. Free of paraben, mineral oil, alcohol, colourant, fragrance.",
        texture="light serum",
        heroes=[("Bakuchiol", "Bakuchiol"), ("Peptide", None), ("Hyaluronic Acid", "Hyaluronic Acid"), ("Niacinamide", "Niacinamide")],
        concerns=[("fine-lines-wrinkles", 3, OP, "Primary purpose."), ("loss-of-firmness", 2, OP, "Positioned for firmness."), ("dehydration", 1, OP, "HA filler technology.")],
        skin=[("normal", "ideal", II), ("dry", "ideal", II), ("combination", "ideal", II), ("sensitive", "good", II), ("oily", "good", II)],
        step=("treatment-serum", 1, 1, "daily", "The retinoid-free option: suitable for mornings and for people who cannot tolerate Resurface.")),
    "Advanced Anti-Melasma Serum": dict(
        summary="Dark-patch serum 'for people with melasma-type and sun spots — look lighter in 7 days' per official copy. Ten actives with Slow-Release Fast Action Technology: niacinamide, tranexamic acid, hyaluronate, Aura-Peptide capsules, Pollu-Shield anti-pollution.",
        texture="serum",
        heroes=[("Niacinamide", "Niacinamide"), ("Tranexamic Acid", "Tranexamic Acid"), ("Hyaluronate", "Sodium Hyaluronate"), ("Aura-Peptide Capsule", None), ("Pollu-Shield", None)],
        concerns=[("melasma", 3, OP, "Primary purpose."), ("dark-spots-sun", 3, OP, "Primary purpose."), ("dullness-uneven-tone", 2, OP, "Tone-evening."), ("post-acne-marks", 2, II, "TXA + niacinamide.")],
        skin=[("normal", "ideal", II), ("combination", "ideal", II), ("dry", "good", II), ("oily", "good", II), ("sensitive", "good", OP)],
        step=("treatment-serum", 1, 1, "daily", "Results depend on strict daily sunscreen.")),
    "Original Powder Mask": dict(
        summary="The 1948 original-recipe Srichand powder, used as a wash-off face mask: calamine-based, absorbs excess oil. Officially for very oily skin and outdoor lifestyles. Free of alcohol, paraben, mineral oil, silicone; not tested on animals.",
        texture="loose powder (mix with water)",
        heroes=[("Calamine", "Calamine")],
        concerns=[("excess-sebum-shine", 3, OP, "Primary purpose."), ("blackheads-congestion", 1, OP, "Reduces the oil that leads to clogging.")],
        skin=[("oily", "ideal", OP), ("acne-prone", "good", OP), ("combination", "good", II), ("dry", "caution", II), ("sensitive", "caution", II)],
        step=("mask", 0, 1, "1–2× weekly", "Mix with water to a paste, leave 10–15 minutes on the T-zone, rinse.")),
    "Sunlution Acne Care Sunscreen": dict(
        summary="'Blocks breakouts, tames oil' — anti-acne sunscreen SPF50+ PA++++ with Triple Protection (UVA/UVB, pollution, blue light), encapsulated Salicylic Acid Sphere, Sun Lock light texture and an oil-absorbing Micro-blur Primer effect.",
        texture="light lotion, matte",
        finish="matte",
        heroes=[("Salicylic Acid Sphere", "Salicylic Acid"), ("Ultra Protect X3", None), ("Micro-blur Primer", "Silica")],
        concerns=[("daily-uv-protection", 3, OP, "Sunscreen."), ("excess-sebum-shine", 3, OP, "Matte, oil-absorbing."), ("acne-breakouts", 2, OP, "Salicylic acid sphere."), ("enlarged-pores", 2, OP, "Micro-blur primer effect."), ("post-acne-marks", 2, II, "UV protection is the first step for marks.")],
        skin=[("oily", "ideal", OP), ("acne-prone", "ideal", OP), ("combination", "ideal", II), ("normal", "good", II), ("dry", "caution", II)],
        step=("sunscreen", 1, 0, "every morning; reapply midday", "Two finger-lengths for face and neck. Doubles as a primer.")),
    "Sunlution Skin Whitening Sunscreen": dict(
        summary="'Blocks dullness' — brightening sunscreen SPF50+ PA++++ with Triple Protection, vitamins B3 and C, Sun Lock texture and a pore-blurring Micro-blur Primer effect; official copy says it can replace a makeup base.",
        texture="light lotion",
        heroes=[("Vitamin B3", "Niacinamide"), ("Vitamin C", None), ("Ultra Protect X3", None), ("Micro-blur Primer", "Silica")],
        concerns=[("daily-uv-protection", 3, OP, "Sunscreen."), ("dullness-uneven-tone", 2, OP, "Brightening-positioned."), ("dark-spots-sun", 2, II, "UV protection prevents spots darkening."), ("enlarged-pores", 1, OP, "Blur effect.")],
        skin=[("normal", "ideal", II), ("combination", "ideal", II), ("oily", "good", II), ("dry", "good", II)],
        step=("sunscreen", 1, 0, "every morning; reapply midday", "Works as a makeup base.")),
    "Sunlution Rosia Ultra Protection Serum Sunscreen": dict(
        summary="Serum sunscreen SPF50+ PA++++ with Damask-rose 'Rosia Transferosome' SPF booster; covers UVA/UVB/long-UVA, blue light and pollution. Oil control 8 hours, water-resistant up to 80 minutes, washes off with a normal cleanser. Vitamins C, B5, B6, B12 and minerals. Free of paraben, mineral oil, colourant, alcohol.",
        texture="serum",
        heroes=[("Rosia Transferosome", None), ("Vitamin C", None), ("Vitamin B5", "Panthenol"), ("3D Water Drench", None)],
        concerns=[("daily-uv-protection", 3, OP, "Sunscreen; the water-resistant choice."), ("fine-lines-wrinkles", 2, OP, "Anti-photoageing positioning."), ("dullness-uneven-tone", 1, OP, "Vitamin C."), ("dehydration", 1, OP, "Hydrating serum texture.")],
        skin=[("normal", "ideal", II), ("combination", "ideal", II), ("dry", "ideal", II), ("oily", "good", OP), ("sensitive", "good", II)],
        step=("sunscreen", 1, 0, "every morning; the pick for outdoor / sweaty days", None)),
    "Sunlution Moisture Burst Watery Sunscreen": dict(
        summary="Watery hydrating sunscreen SPF50+ PA++++: HYDRO FILM / HYDRO PUMPER, 15-HYA complex, ectoin postbiotic and five ceramides; claims 8-hour hydration. Reef-safe, vegan; free of paraben, alcohol, comedogenic silicone, synthetic colour, triethanolamine. Official copy: for dry, combination and oily skin.",
        texture="watery gel",
        finish="glowy",
        heroes=[("15HYA Complex", "Sodium Hyaluronate"), ("Ectoin Postbiotic", "Ectoin"), ("5X Ceramix", "Ceramide NP")],
        concerns=[("daily-uv-protection", 3, OP, "Sunscreen."), ("dehydration", 3, OP, "Hydration-first sunscreen."), ("compromised-barrier", 2, OP, "Five ceramides + ectoin."), ("dryness", 2, OP, "Dewy finish.")],
        skin=[("dry", "ideal", OP), ("dehydrated-oily", "ideal", II), ("normal", "ideal", II), ("combination", "good", OP), ("sensitive", "good", II), ("oily", "good", OP)],
        step=("sunscreen", 1, 0, "every morning; reapply midday", None)),
    "Sunlution Tone Up Serum Sunscreen": dict(
        summary="Pink-beige tone-up serum sunscreen SPF50+ PA++++: AURABRIGHT boosting technology brightens one level instantly and blurs pores; Hybrid-Shield protection against UVA/UVB and blue light; peach, camu-camu and butterfly-bush extracts. Dermatologically tested.",
        texture="tinted serum",
        finish="tone_up",
        heroes=[("Prunus Persica (Peach) Fruit Extract", None), ("Myrciaria Dubia (Camu Camu) Fruit Extract", None), ("Buddleja Officinalis Flower Extract", None)],
        concerns=[("daily-uv-protection", 3, OP, "Sunscreen."), ("dullness-uneven-tone", 3, OP, "Instant tone-up."), ("natural-everyday-base", 2, OP, "Can replace base on no-makeup days."), ("enlarged-pores", 1, OP, "Blur effect.")],
        skin=[("normal", "ideal", II), ("combination", "ideal", II), ("oily", "good", II), ("dry", "good", II)],
        step=("sunscreen", 1, 0, "every morning", "Tone-up tint suits light-to-medium skin best; check on deeper tones.")),
    "Translucent Powder": dict(
        summary="The heritage hero (relaunched 2014; one of Thailand's best-selling face powders): a translucent loose powder that blurs pores and controls oil on every skin tone without shifting foundation colour. Official copy: fragrance-free, paraben-free, not tested on animals, travel lock lid. INCI is published as raw-material blends (talc, silica, lauroyl lysine…) and lists no fragrance.",
        texture="loose powder", finish="matte",
        heroes=[("Translucent powder base (Talc, Silica)", "Silica")],
        concerns=[("excess-sebum-shine", 3, OP, "Primary purpose: oil control."), ("makeup-longevity-oil-control", 3, OP, "Sets base without changing its colour."), ("enlarged-pores", 2, OP, "Official tagline: blurs pores.")],
        skin=[("oily", "ideal", OP), ("combination", "ideal", OP), ("acne-prone", "good", II), ("normal", "good", OP), ("dry", "caution", II)],
        step=("powder", 1, 0, "daily + midday touch-up", "Press onto the T-zone with a puff; dust the rest with a brush.")),
    # ---- SASI skincare
    "Acne Sol Calming Toner Pad": dict(
        summary="SASI leave-on toner pad for blemish-prone skin with Salicylic Acid (BHA) for gentle exfoliation, 8 natural extracts, dipotassium glycyrrhizate, cica and glyceryl glucoside. For all skin types incl. very oily; free of alcohol, paraben, mineral oil, silicone, fragrance and colour. This is the only leave-on BHA step in the company's portfolio.",
        texture="soaked pad",
        heroes=[("Salicylic Acid", "Salicylic Acid"), ("Dipotassium Glycyrrhizate, CICA", "Dipotassium Glycyrrhizate"), ("Glyceryl Glucoside", "Glyceryl Glucoside"), ("8 Natural Extracts", None)],
        concerns=[("blackheads-congestion", 3, OP, "Leave-on BHA."), ("acne-breakouts", 3, OP, "Primary purpose."), ("excess-sebum-shine", 2, II, "BHA is oil-soluble."), ("enlarged-pores", 2, II, "Keeps pores clear."), ("rough-texture", 1, OP, "Gentle exfoliation.")],
        skin=[("oily", "ideal", OP), ("acne-prone", "ideal", OP), ("combination", "ideal", OP), ("normal", "good", OP), ("dry", "caution", II), ("sensitive", "caution", II)],
        step=("toner-pad", 0, 1, "3 nights/week, building to nightly if comfortable", "Swipe over T-zone after cleansing. Not on Resurface nights at first. BHA concentration is not disclosed.")),
    "Whitening Moisture Toner Pad": dict(
        summary="SASI brightening toner pad: niacinamide, sea-buckthorn, witch hazel, Korean probiotic, plus Salicylic Acid (BHA), 8 natural extracts, dipotassium glycyrrhizate and cica. For all skin types; free of alcohol, paraben, mineral oil, silicone, fragrance and colour.",
        texture="soaked pad",
        heroes=[("Niacinamide", "Niacinamide"), ("Sea-buckthorn Extract", "Hippophae Rhamnoides Fruit Extract"), ("Witch Hazel", "Hamamelis Virginiana (Witch Hazel) Extract"), ("Salicylic Acid (BHA)", "Salicylic Acid"), ("Probiotic", "Lactobacillus Ferment")],
        concerns=[("post-acne-marks", 3, OP, "Primary purpose."), ("dullness-uneven-tone", 2, OP, "Brightening."), ("enlarged-pores", 2, OP, "Witch hazel + BHA."), ("blackheads-congestion", 1, OP, "Contains BHA.")],
        skin=[("oily", "ideal", OP), ("combination", "ideal", OP), ("normal", "ideal", OP), ("acne-prone", "good", OP), ("dry", "good", OP), ("sensitive", "caution", II)],
        step=("toner-pad", 0, 1, "3 nights/week, building up", None)),
    "Acne Sol 2-in-1 Double Cleansing Gel": dict(
        summary="SASI one-step makeup-removing gel cleanser for blemish-prone skin: nano-encapsulated Salicylic Acid (slow release), cica, tea tree oil, bisabolol, zinc PCA, red clover. Free of alcohol, fragrance, paraben, silicone, SLS and soap.",
        texture="gel",
        heroes=[("Salicylic Acid (Nano Encapsulation)", "Salicylic Acid"), ("Cica", "Centella Asiatica Extract"), ("Tea Tree Oil", "Melaleuca Alternifolia (Tea Tree) Leaf Oil"), ("Bisabolol", "Bisabolol"), ("Zinc PCA", "Zinc PCA")],
        concerns=[("acne-breakouts", 2, OP, "Primary positioning."), ("excess-sebum-shine", 2, OP, "Balances oil."), ("blackheads-congestion", 1, OP, "Rinse-off BHA.")],
        skin=[("oily", "ideal", OP), ("acne-prone", "ideal", OP), ("combination", "good", II), ("sensitive", "caution", II)],
        step=("cleanse", 1, 1, "daily", "Removes light makeup in one step.")),
    "Acne Sol Micellar Cleansing Water": dict(
        summary="SASI micellar water for blemish-prone skin: Triple-Micellar Technology with cica, Jeju aloe and tea tree oil; dermatologist-tested non-irritating.",
        texture="micellar water",
        heroes=[("Cica Extract", "Centella Asiatica Extract"), ("Tea Tree Oil", "Melaleuca Alternifolia (Tea Tree) Leaf Oil"), ("Jeju Aloe Vera", None)],
        concerns=[("acne-breakouts", 1, OP, "For blemish-prone skin."), ("excess-sebum-shine", 1, OP, "Reduces excess oil.")],
        skin=[("oily", "ideal", OP), ("acne-prone", "ideal", OP), ("combination", "good", II)],
        step=("makeup-removal", 0, 1, "on makeup days", None)),
    "Acne Sol Comfort Sunscreen": dict(
        summary="SASI non-clogging serum sunscreen SPF50+ PA++++ for blemish-prone skin: Triple UV Filter, Salicylic Acid, cica, vitamin B3, 'Miracle Powder' oil control for 9 hours. Alcohol-, paraben-, colourant-, mineral-oil-free; dermatologist tested.",
        texture="serum",
        finish="matte",
        heroes=[("Salicylic Acid", "Salicylic Acid"), ("Cica", "Centella Asiatica Extract"), ("Vitamin B3", "Niacinamide"), ("Miracle Powder", "Silica")],
        concerns=[("daily-uv-protection", 3, OP, "Sunscreen."), ("acne-breakouts", 2, OP, "Blemish-prone positioning."), ("excess-sebum-shine", 3, OP, "9-hour oil control claim.")],
        skin=[("oily", "ideal", OP), ("acne-prone", "ideal", OP), ("combination", "good", II)],
        step=("sunscreen", 1, 0, "every morning", "Budget teen-friendly option (15 ml).")),
    "Girls Can 3-in-1 Tone Up & Primer Sunscreen": dict(
        summary="SASI pink-white tone-up + primer + sunscreen SPF50+ PA++++: Color Correct Booster, Skin Fitting Polymer blur, 12-hour oil control claim, 2% vitamin B3 and sweet cherry. Water- and sweat-resistant.",
        texture="tinted cream",
        finish="tone_up",
        heroes=[("2% Vitamin B3", "Niacinamide"), ("Sweet Cherry", None), ("Color Correct Booster", None)],
        concerns=[("daily-uv-protection", 3, OP, "Sunscreen."), ("dullness-uneven-tone", 2, OP, "Tone-up."), ("makeup-longevity-oil-control", 2, OP, "Primer + 12 h oil control.")],
        skin=[("oily", "ideal", OP), ("combination", "ideal", II), ("normal", "good", II)],
        step=("sunscreen", 1, 0, "every morning", "Sachet format (5 ml).")),
}

LINE_POSITIONING = {
    "skin-moisture-burst": ("Hydration and everyday maintenance; light textures for a humid climate.", ["Glyceryl Glucoside", "Hyaluronic Acid", "Trehalose", "Niacinamide", "Panthenol", "Centella Asiatica"]),
    "barrier-boost": ("Sensitive, reactive or over-treated skin; barrier recovery. Irritation-tested on sensitive skin.", ["Ectoin", "Cicazome (Cica-Phytosome)", "Chestnut Leaf Extract", "Dipotassium Glycyrrhizate"]),
    "phyto-camellia-pdrn": ("Glow and even tone with disclosed actives: plant PDRN 0.5%, niacinamide up to 5%, alpha-arbutin 0.1%.", ["Phyto Camellia PDRN", "Niacinamide", "Alpha Arbutin"]),
    "super-c": ("Dark spots, post-blemish marks and dullness; vitamin-C derivatives with tranexamic acid and arbutin. The gel cream adds glycolic acid (AHA).", ["Vitamin C derivatives", "Sea Buckthorn", "Tranexamic Acid", "Alpha Arbutin", "Niacinamide", "Glycolic Acid"]),
    "resurface": ("The retinoid step: hydroxypinacolone retinoate (HPR) in a tolerance-first base.", ["Hydroxypinacolone Retinoate", "Peptides", "Hyaluronic Acid + Ceramide", "Niacinamide"]),
    "timeless": ("Retinoid-free anti-ageing built on bakuchiol.", ["Bakuchiol", "Peptide", "Hyaluronic Acid", "Niacinamide"]),
    "advanced-anti-melasma": ("Stubborn dark patches: tranexamic acid + niacinamide with anti-pollution shield.", ["Tranexamic Acid", "Niacinamide", "Aura-Peptide", "Pollu-Shield"]),
    "sunlution": ("Daily photoprotection SPF50+ PA++++ in five textures: Acne Care (matte, salicylic acid), Skin Whitening (brightening base), Rosia (water-resistant serum), Moisture Burst Watery (hydrating, reef-safe), Tone Up (tinted).", None),
    "translucent-powder": ("The heritage hero: fragrance-free translucent loose powder for oil control on every skin tone.", None),
    "bare-to-perfect": ("Translucent and colour-correcting powders for a bare-skin finish.", None),
    "skin-essential": ("'Fine Smooth' natural matte base family (2026 renewal): foundation, cushion, concealer, foundation powder in six shades.", ["Niacinamide", "Tocopheryl Acetate", "Hya Complex", "Rosa Centifolia", "CICA"]),
    "super-coverage": ("Full-coverage, always-matte base for oily skin and long wear.", None),
    "skin-booster": ("Skincare-infused serum foundation (86% skincare base) for a hydrated look.", None),
    "enchanted": ("Soft-matte, medium-to-full coverage base and colour collection.", None),
    "acne-sol": ("SASI's blemish-prone line for teens and young adults: salicylic acid, cica, tea tree across cleanser, toner pad, sunscreen, cushion, concealer and powder.", ["Salicylic Acid", "Cica", "Tea Tree Oil"]),
}

# The honest gap list. closest = products.name_en
RANGE_GAPS = [
    dict(slug="dedicated-bha-treatment", title="No dedicated leave-on BHA treatment under the SRICHAND brand", missing="BHA (salicylic acid) serum / toner with a disclosed strength",
         severity="high",
         why="Oil-soluble exfoliation is the highest-return step for shine, congestion and blackheads — the dominant concern in a hot, humid market and the heart of Srichand's oil-control heritage. Salicylic acid does exist in the portfolio — it is on the official INCI of 13 products (Sunlution Acne Care at #32 of 54, plus 12 SASI products led by the Acne Sol line) — but never as a SRICHAND-brand leave-on treatment and never with a stated percentage.",
         closest="Acne Sol Calming Toner Pad", closest_limits="A SASI (sister-brand) pad with undisclosed BHA strength; fine for maintenance, may be too mild for established congestion.",
         generic_en="A 2% salicylic acid (BHA) leave-on liquid or toner from a pharmacy or drugstore, used 2–3 nights a week.",
         generic_th="ผลิตภัณฑ์ BHA (ซาลิไซลิก แอซิด) 2% แบบไม่ต้องล้างออก จากร้านขายยาหรือร้านเครื่องสำอางทั่วไป ใช้สัปดาห์ละ 2–3 คืน",
         commercial="Clearest white-space SKU: a 'Sunlution-grade' BHA serum or pad under SRICHAND IN-SKIN would sit directly on the brand's oil-control equity.",
         concerns=["blackheads-congestion", "acne-breakouts", "excess-sebum-shine", "enlarged-pores"]),
    dict(slug="azelaic-acid", title="No azelaic acid product", missing="Azelaic acid 10% class",
         severity="medium",
         why="Azelaic acid is the best-tolerated single answer for redness that coexists with post-blemish marks, and is usable where retinoids are not.",
         closest="Advanced Anti-Melasma Serum", closest_limits="Covers the marks (tranexamic acid + niacinamide) but not the redness / bumps side.",
         generic_en="An azelaic acid 10% cream or gel from a pharmacy; above 10% is a medicine — ask a pharmacist.",
         generic_th="ครีมหรือเจลอะเซลาอิก แอซิด 10% จากร้านขายยา (ความเข้มข้นสูงกว่านี้จัดเป็นยา ควรปรึกษาเภสัชกร)",
         commercial="Natural partner to the Barrier Boost line for the 'sensitive but blemish-prone' customer.",
         concerns=["sensitivity-redness", "post-acne-marks", "acne-breakouts"]),
    dict(slug="medical-acne-care", title="Persistent or inflammatory acne needs medicine, not cosmetics", missing="Drug-class actives (e.g. adapalene, benzoyl peroxide)",
         severity="medium",
         why="Thai law classes acne treatment as a drug claim. For moderate-to-severe or scarring acne the honest answer is outside any cosmetic range.",
         closest="Sunlution Acne Care Sunscreen", closest_limits="Supports a routine for blemish-prone skin; does not treat acne.",
         generic_en="See a pharmacist or dermatologist about a topical acne medicine. Keep the routine around it gentle: Barrier Boost cleanser and gel cream, Sunlution Acne Care.",
         generic_th="แนะนำปรึกษาเภสัชกรหรือแพทย์ผิวหนังเรื่องยาทาสิว และดูแลผิวควบคู่ด้วยผลิตภัณฑ์ที่อ่อนโยน",
         commercial="Referral honesty builds the trust that sells the supporting routine (cleanser, barrier care, sunscreen).",
         concerns=["acne-breakouts"]),
    dict(slug="eye-care", title="No dedicated eye product", missing="Eye cream / eye serum",
         severity="low",
         why="Frequently requested. Low clinical necessity, but matters for basket size and for under-eye concerns the advisor will detect in photos.",
         closest="Skin Essential Fine Smooth Concealer", closest_limits="Covers under-eye darkness cosmetically; no treatment benefit.",
         generic_en="Any fragrance-free eye cream with caffeine or peptides; or simply tap your facial moisturiser around the orbital bone.",
         generic_th="อายครีมสูตรไม่มีน้ำหอมที่มีคาเฟอีนหรือเปปไทด์ หรือใช้มอยส์เจอร์ไรเซอร์แตะเบา ๆ รอบดวงตา",
         commercial="Easy line extension for Timeless or Phyto Camellia PDRN.",
         concerns=["under-eye-darkness", "fine-lines-wrinkles"]),
    dict(slug="body-sun-care", title="No body sunscreen or body care", missing="Body SPF / body lotion",
         severity="low",
         why="Face-only sun protection leaves neck, arms and hands exposed; customers ask for a matching body product.",
         closest="Sunlution Rosia Ultra Protection Serum Sunscreen", closest_limits="Water-resistant and pleasant, but 40 ml is a face size — uneconomical for body.",
         generic_en="A body sunscreen SPF50+ PA++++ in a 100 ml+ size from any drugstore.",
         generic_th="กันแดดทาตัว SPF50+ PA++++ ขนาด 100 มล. ขึ้นไป จากร้านทั่วไป",
         commercial="Sunlution has the filter technology and brand permission to extend to body.",
         concerns=["daily-uv-protection"]),
]


BRAND_INFO = {   # source: research/findings/rewards_policies_brand.md
    "srichand": dict(positioning="Thai heritage beauty house founded in 1948 (Srichand United Dispensary Co., Ltd.; rebranded 2014; CEO Rawit Hanutsaha). Known for the Translucent Powder; now spans IN-SKIN skincare, Sunlution sunscreen, base and colour makeup.",
                     target_audience="Mass-market women (and increasingly men) roughly 20–45 who want proven, climate-appropriate products at drugstore prices."),
    "sasi": dict(positioning="Srichand's younger sister brand, launched 2017: playful colour makeup and the Acne Sol blemish-care line at value prices.",
                 target_audience="Teens and young adults, roughly 16–35; first-time makeup and skincare buyers."),
    "srichand-baby": dict(positioning="Baby powders under the Srichand name.", target_audience="Parents of infants and young children."),
}
